### ISSUE TITLE
Requested VAA not found in store (transfer of USDC from ETH to BSC)

### ISSUE THREAD

**Issue by pepeirosa** [wormhole-foundation/wormhole#1014]
I have a problem, I send 100USDC from ETH to BSC, but not finish the transaction. The last step are:

Waiting for Wormhole Network consensus.

I went to redeem page, and put the transaction:

0xce6dfd731ce970c927fb50c7cdedbbd4f4cf21494c2be9b769d5889f1b7747db

, but is impossible redeem my assets, the error shown is:

requested VAA not found in store

What is the problem?

**Comment by suzzax** [comment]
User has redeemed the funds. Please close this issue.
