### ISSUE TITLE
Set local devnet failed 

### ISSUE THREAD

**Issue by Randyshu2018** [wormhole-foundation/wormhole#1097]
**Description**
I followed [official doc](https://github.com/certusone/wormhole/blob/dev.v2/DEVELOP.md) to set up devnet ,but it failed

**Env**
```
os: Darwin
minikube version: v1.21.0
docker version 20.10.14, build a224086
```

**Step to Reproduce**
 ```
  1. docker enable minikube
  2. minikube ssh 'echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p'
  3. minikube start
  4. kubectl config set-context --current --namespace=wormhole
  5. git clone https://github.com/certusone/wormhole.git
  6. cd wormhole
  7. tilt up -- --num=1
  ```

**Expect behavior**
build successfully 

**Screenshots**
<img width="1665" alt="image" src="https://user-images.githubusercontent.com/19544447/164358873-44f79e9e-4742-4635-9bbf-df229924c58e.png">

I have searched for this issue with google, maybe rust version out of date or solana version is mismatch ,but I 'm not familiar with rust, so ...

**Comment by evan-gray** [comment]
Hi @Randyshu2018. Are you on an M1 Mac? The Solana container isn’t currently compatible with ARM due to the Solana installer not including `build-bpf`. I think if you pass the flag `--solana=false` Tilt will start up without it. Otherwise, the container would need to be converted to build Solana from source.

**Comment by Randyshu2018** [comment]
> Hi @Randyshu2018. Are you on an M1 Mac? The Solana container isn’t currently compatible with ARM due to the Solana installer not including `build-bpf`. I think if you pass the flag `--solana=false` Tilt will start up without it. Otherwise, the container would need to be converted to build Solana from source.

intel.  I have fixed this issue and another problem is solana build takes too long time ... I have compiled for 3 hours, so is there any news way to accelerate it?

**Comment by Randyshu2018** [comment]
> Hi @Randyshu2018. Are you on an M1 Mac? The Solana container isn’t currently compatible with ARM due to the Solana installer not including `build-bpf`. I think if you pass the flag `--solana=false` Tilt will start up without it. Otherwise, the container would need to be converted to build Solana from source.

if disable solana the wormhole-example can not run normally ...

**Comment by Randyshu2018** [comment]
> > Hi @Randyshu2018. Are you on an M1 Mac? The Solana container isn’t currently compatible with ARM due to the Solana installer not including `build-bpf`. I think if you pass the flag `--solana=false` Tilt will start up without it. Otherwise, the container would need to be converted to build Solana from source.
> 
> if disable solana the wormhole-example can not run normally ...

there are some issue when building devnet using minikube 
1. solana-devnet
```
[event: pod wormhole/solana-devnet-0] Back-off restarting failed container
Detected container restart. Pod: solana-devnet-0. Container: devnet.
[devnet] 
[devnet] Notice! No wallet available. `solana airdrop` localnet SOL after creating one
[devnet] 
```
2. guardian-0
```
Detected container restart. Pod: guardian-0. Container: guardiand.

        +++++++++++++++++++++++++++++++++++++++++++++++++++
        |   NODE IS RUNNING IN INSECURE DEVELOPMENT MODE  |
        |                                                 |
        |      Do not use -unsafeDevMode in prod.         |
        +++++++++++++++++++++++++++++++++++++++++++++++++++

2022-04-27T03:27:51.161Z	INFO	guardian-0	status server listening on [::]:6060
badger 2022/04/27 03:27:52 INFO: All 0 tables opened in 0s
badger 2022/04/27 03:27:52 INFO: Discard stats nextEmptySlot: 0
badger 2022/04/27 03:27:52 INFO: Set nextTxnTs to 0
```

**Comment by spacemandev-git** [comment]
Hey @Randyshu2018 I seem to be unable to reproduce your issue, the minikube command is able to run solana fine....is there any other information you could provide to help me reproduce?

**Comment by evan-gray** [comment]
Closing since this has been inactive. There’s been some improvements plus more options outlined in https://book.wormhole.com/technical/env/environments.html
