### ISSUE TITLE
Error: requested VAA not found in store

### ISSUE THREAD

**Issue by wlunadev** [wormhole-foundation/wormhole#1525]
My transaction was initiated a day ago, but still unable to retrieve for redemption. 
https://solscan.io/tx/4DdYrUrzQnfPPq9JrTeCMDT1ZFMwnbYFddJJs14Vf3efCwtEfad84FkTjyHfEpYuq1BQVSfuMu1JNBU74V6UNhHm

**Comment by evan-gray** [comment]
Closing as this transfer has already been redeemed.
