### ISSUE TITLE
TOB-WORM-1: Make Solana contracts testable outside of Tilt

### ISSUE THREAD

**Issue by tbjump** [wormhole-foundation/wormhole#1528]
Currently, one needs to run Tilt to run the Solana contract tests. It should be possible to run them without Tilt since Tilt is pretty heavyweight.

**Comment by evan-gray** [comment]
@tbjump  does https://github.com/wormhole-foundation/wormhole/blob/0f7ddda602acaec7d50cebe56a4cbb88524c643c/solana/Makefile#L91 / https://github.com/wormhole-foundation/wormhole/blob/dev.v2/.github/workflows/build.yml#L84 satisfy closing this issue?

**Comment by tbjump** [comment]
Thanks to the pointer. I think it should be made a script and added it to the solana/README.md such that developers can more easily find it and run the tests locally instead of in the github action.

**Comment by evan-gray** [comment]
Closing this as running `make test` seems sufficient. The upcoming rewrite should also refine some documentation clarity.
