### ISSUE TITLE
TOB-WORM-1: Make Solana contracts buildable and verifiable from source

### ISSUE THREAD

**Issue by tbjump** [wormhole-foundation/wormhole#1529]
## Expected Behavior

One should be able to build and verify the solana contracts from source to protect against the threat of compromised binary images. 

## Current Behavior

[Building](https://github.com/wormhole-foundation/wormhole/blob/dev.v2/solana/Makefile) the solana contracts and verifying them currently depends on a [docker image](https://github.com/wormhole-foundation/wormhole/blob/dev.v2/solana/Dockerfile) in the wormhole ghcr.io.

**Comment by kcsongor** [comment]
The toolchain does not produce deterministic builds, so the only way to have reproducible output is by building in a docker image. What would be a good alternative solution?

**Comment by tbjump** [comment]
@kcsongor do you know why the toolchain doesn't produce deterministic builds?

**Comment by kcsongor** [comment]
the installer pulls in a bunch of external dependencies, some unpinned, some through http, some get periodically yanked from the repo. We took a snapshot and use that to mitigate against these externalities

**Comment by evan-gray** [comment]
I find @kcsongor 's explanation to be sufficient.
