### ISSUE TITLE
TOB-WORM-9: cw20-wrapped tests do not build

### ISSUE THREAD

**Issue by tbjump** [wormhole-foundation/wormhole#1534]
Severity: Informational
Target: cosmwasm/contracts/cw20-wrapped/src/contract.rs, cosmwasm/Makefile

Description
The cw20-wrapped package’s tests do not build.

**Comment by evan-gray** [comment]
@tbjump  do you agree?

**Comment by tbjump** [comment]
yes, thanks @kii-dot
