### ISSUE TITLE
Unknown Messages

### ISSUE THREAD

**Issue by przmyst** [wormhole-foundation/wormhole#1573]
I assume you're aware of this, but I'm curious what's going on with these undefined emitterChain transactions? They're really clogging up the explorer feed.

[Unknown Message - Sequence 0](https://europe-west3-wormhole-315720.cloudfunctions.net/mainnet-readrow?emitterChain=26&emitterAddress=f8cd23c2ab91237730770bbea08d61005cdda0984348f3f6eecb559638c0bba0&sequence=0)

**Comment by hendrikhofstadt** [comment]
Now being flagged as Pyth price updates
