### ISSUE TITLE
Ping utility

### ISSUE THREAD

**Issue by leoluk** [wormhole-foundation/wormhole#161]

**Comment by leoluk** [comment]
I think we should still have some kind of automated ping as long as usage is low

**Comment by hendrikhofstadt** [comment]
Ah ok I thought this was talking about the old ping mechanism. A "keep-alive" ping sonuds like a good idea

**Comment by hendrikhofstadt** [comment]
@aadam-10 the goal is to periodically send messages on all networks to catch failures that would otherwise go unnoticed. This may fit into what @evan-gray planned for the staging environment.

**Comment by evan-gray** [comment]
A group of us plan to take this up as a larger project. Will recreate as a milestone.
