### ISSUE TITLE
Wormhole(Testnet)

### ISSUE THREAD

**Issue by Abhishek1857** [wormhole-foundation/wormhole#1684]
Hey, i have a question that if we do tilt up we get connect to local devnets so how can be connect to already runnning testnets like rinkeby,ropsten etc .

**Comment by kev1n-peters** [comment]
You can interact with the testnet contracts deployed at the addresses for each chain specified here: https://github.com/wormhole-foundation/wormhole/blob/dev.v2/sdk/js/src/utils/consts.ts#L232 using a web3 client or your testnet contract. There's also an example UI that can be used to interact with the testnet contracts: https://github.com/wormhole-foundation/example-token-bridge-ui

**Comment by evan-gray** [comment]
Also, the testnet guardian is https://wormhole-v2-testnet-api.certus.one 🙂 
You can also find this info in the book
https://book.wormhole.com/reference/contracts.html
https://book.wormhole.com/reference/rpcnodes.html
