### ISSUE TITLE
Wormhole(Testnet)

### ISSUE THREAD

**Issue by Abhishek1857** [wormhole-foundation/wormhole#1692]
How to run wormhole in testnet

**Comment by evan-gray** [comment]
Please do not open duplicate issues. Your previous issue, #1684, was answered and closed. You will need to elaborate with what the bug or requested change to Wormhole is. For developer support, Discord or the discussions are a more appropriate place. 

As detailed in the previous issue, there is a public guardian and contract network deployed for testnet detailed here:

https://book.wormhole.com/reference/contracts.html#testnet
https://book.wormhole.com/reference/rpcnodes.html#testnet-guardian-rpc
