### ISSUE TITLE
Waiting for Wormhole Network consensus...

### ISSUE THREAD

**Issue by marioa2401** [wormhole-foundation/wormhole#1723]
i have tried to send wbnb from solana to bsc and its been stuck for an hour it has been approved on in the solana side but in in the bsc side ... can someone please assist me ? I don't know what to do ... here is the transaction
https://solscan.io/tx/5vt6gqcNZaEt9eDLr65iKQ71LgnHQNjrBs7TVYaTVrnTYWDh39EJGLg6s3dsW4UY1KYgwbiHM8Xjc7LvZMcQhkVP

**Comment by evan-gray** [comment]
Per the issue template,

> Github issues are **ONLY** for reporting bugs. 
> 
> For user support questions such as VAA not found, please use the [Wormhole Official Discord](https://discord.gg/wormholecrypto). Do not give your wallet private key or mnemonic words to anyone.
