### ISSUE TITLE
NEAR Web Wallet Asks for Full ACCESS on Wormhole Bridge dApp

### ISSUE THREAD

**Issue by codingshot** [wormhole-foundation/wormhole#1752]
Github issues are **ONLY** for reporting bugs. Before contributing new features (such as a new chain) please first read the [contribution frequently asked questions](https://github.com/wormhole-foundation/wormhole/blob/dev.v2/CONTRIBUTING.md#contributions-faq).

For user support questions such as VAA not found, please use the [Wormhole Official Discord](https://discord.gg/wormholecrypto). Do not give your wallet private key or mnemonic words to anyone.

On the bridge. When connected the applications as for full access on the web wallet.

## Expected Behavior
Access for permission for selected functions. Essentially approving this means wormhole has full control of your wallet.

## Current Behavior

Web Wallet prompts for full access.

## Possible Solution

Function access.

## Steps to Reproduce

Portalbridge.com -> Select NEAR -> Wallet Selector (choose Web Based Wallet) -> Approval Page

## Context (Environment)
Not using wormhole because its suspect.

**Comment by evan-gray** [comment]
Closing because, assuming you’re referring to portalbridge.com, that app is not associated with this repo. That said, I would recommend using am extension wallet instead which does not require any such permission and works like all the other wallets you’re likely used to.
