### ISSUE TITLE
Refactor validation logic into VAA for better reuse.

### ISSUE THREAD

**Issue by gabzim** [wormhole-foundation/wormhole#1764]
## Expected Behavior

I'm trying to validate a VAA off-chain. While the VAA offers a `VerifySignatures(guardianSetKeys)` method, this only checks for signatures as the name implies, and I see that the `Processor#handleInboundSignedVAAWithQuorum` (in `node/pkg/processor/observation.go`) performs additional checks like reaching quorum and that the VAA has len(signatures) > 0. 

## Current Behavior

You need to remember to copy/paste those checks if you want to be sure your VAA is valid in a different project that leverages the node's code to connect to the gossip network.

## Possible Solution

Maybe we can either export a top level function or add a method to the VAA struct that performs this extended validation? It would need to receive the guardianset and the quorum int (or the guardianset could calculate its quorum instead of the `CalculateQuorum` being in the `processor` package).

## Steps to Reproduce

N/A

## Context (Environment)

Building an indexer for the wormhole ecosystem.

**Comment by panoel** [comment]
This issue was fixed by PR #1779
