### ISSUE TITLE
Remove Ropsten support

### ISSUE THREAD

**Issue by kev1n-peters** [wormhole-foundation/wormhole#1770]
Given that the merge has already occurred and the Ethereum core development team plans to shut down or deprecate the Ropsten testnet soon, wormhole should remove Ropsten support. Removing Ropsten support would entail removing all references of Ropsten in code and documentation. It's probably a good idea to keep the Ropsten Chain ID (`10001`) as reserved so it's not reused.

**Comment by bruce-riley** [comment]
The following PRs address this issue:
PR 1818 - node changes
PR 1819 - sdk/js changes

Once 1819 has been merged and the new sdk released, an additional PR will be needed to remove support from client/js, the relayer and the ethereum tests.

**Comment by bruce-riley** [comment]
PR #1845 removes Ropsten support from the client/js.

**Comment by bruce-riley** [comment]
PR #1845 has been closed because it requires reworking the client, which is beyond the scope of this issue. Additionally, removing Ropsten from the relayer involves significant code changes due to the SDK version bump.
