### ISSUE TITLE
Run Prettier on CI

### ISSUE THREAD

**Issue by evan-gray** [wormhole-foundation/wormhole#1773]
## Expected Behavior

JavaScript / TypeScript formatting checks should be enforced in CI [like Go is](https://github.com/wormhole-foundation/wormhole/blob/dev.v2/.github/workflows/build.yml#L257-L258). I would recommend adopting the standard [prettier](https://prettier.io/) preferences to start.

## Current Behavior

Often times, contributors may make commits without formatting or with different formatting preferences. This can lead to unintended diffs cluttering up reviews.

## Possible Solution

Add a CI step which runs prettier on all `.js(x)` and `.ts(x)` files to ensure nothing would change.

**Comment by tbjump** [comment]
Once we get consensus on the formatting standard to use I can implement it. 
Please react with 👍 if you'd like to adopt https://prettier.io/ for JS/TS or comment with an alternative.

**Comment by tonyjin** [comment]
Closed by #3176
