### ISSUE TITLE
Guardiand should have a simple way to list RPC nodes

### ISSUE THREAD

**Issue by gearlbrace** [wormhole-foundation/wormhole#1810]
Currently the only way to determine RPC nodes is parsing through logs or looking at the startup command/script/unitfile.

Parsing through logs is unwieldy.
If the startup command/script/unitfile has changed on disk but the service has not been restarted then it's no longer a reliable source of which RPC nodes are active.

having something along the lines of "guardiand admin list-rpc" would be a definitive source of which RPC nodes are being referred to.

**Comment by evan-gray** [comment]
This seems reasonable to do, especially as an admin-only command 🙂

**Comment by pires** [comment]
@evan-gray @panoel are you taking on this or can I give it a stab?

**Comment by evan-gray** [comment]
Chatted with @panoel, it's all you @pires 🙂 let us know if you need a hand.

**Comment by pires** [comment]
Thank you, I will!

**Comment by pires** [comment]
I've started working on this but had to pause due to other priorities. I expect to pick it up again next week.
