### ISSUE TITLE
Make Solana ready faster by improving chain registration submissions

### ISSUE THREAD

**Issue by evan-gray** [wormhole-foundation/wormhole#1826]
## Expected Behavior

The containers in tilt should become usable as fast as reasonably possible. If there are obvious optimizations to be made with minimal complexity, they should be made.

## Current Behavior

Every chain registration is performed in series by running `worm submit $VAA --chain solana --network devnet`

https://github.com/wormhole-foundation/wormhole/blob/3877f6f3c3f6f097ae7b3630bd271b8620f3ab6b/solana/devnet_setup.sh#L107

## Possible Solution

`worm submit` performs multiple transactions per VAA and uses a confirmed connection to submit them. Perhaps there are easy devnet-specific improvements to make there. Alternatively, could the registration accounts be generated / dumped and restored? The only downside to that approach would be that the registration flow of the contracts and `worm submit` wouldn't be tested in this way anymore.

## Context (Environment)

Tilt

**Comment by kcsongor** [comment]
🤔
