### ISSUE TITLE
Emit event on complete transfer

### ISSUE THREAD

**Issue by mizdler** [wormhole-foundation/wormhole#1827]
We have a problem and a suggestion that helps teams building on Wormhole.

We think tracking Wormhole transactions across chains is important and can help improve UX for xDapps. 

**Problem:** Tracking "complete transfer" transactions in EVM chains is difficult.

**Current solutions:**
1 - Using payload 3 to write a wrapper contract that emits an event.
While this solution works, it has a couple of drawbacks:
First, it increases the gas cost for end-users
Second, writing a wrapper is not that easy considering the security risks that it brings with it and it's just too much work for a simple token transfer

2 - Index transactions
In Mayan, we are using this approach, but it requires tracer nodes which are expensive and also needs some indexing tools (we are using Thegraph for this)

The second approach has another variant: third-party services that offer webhooks, but these webhooks have their drawbacks.

**Proposal:**
Token bridge emits an event upon complete transfer

**Comment by evan-gray** [comment]
Thanks @mizdler for the write up! I agree this is a great idea that would help all integrators and likely be useful to the [explorer](https://github.com/wormhole-foundation/wormhole-explorer) project as well.

**Comment by evan-gray** [comment]
I’m not sure a wormhole message is more effective than an event 🤔 what is the upside / downside of creating another wormhole message vs using a native event? My initial thought is that a wormhole message would be more difficult for integrators to watch for, but perhaps it’s simply different.

**Comment by jumpsiegel** [comment]
You could use the same spy/fly to watch for redemption that we use to watch for the events in the first place.  Publishing a wormhole message creates a one-size-fits-all solution.

Publishing a native event on each chain, while "cheaper" would then require integrators to effectively write watchers for every chain themselves duplicating the whole guardian functionality.

**Comment by mizdler** [comment]
Won't be a message fee in the future?

**Comment by jumpsiegel** [comment]
That was also a concern and a bigger one.  The right thing to do would make the person receiving the money pay the fee which adds significantly to the implementation complexity.

**Comment by evan-gray** [comment]
If the message was being relayed, I would expect this to simply become integrated into the fee consideration. There is no (other)  mechanism to pass that on to the recipient.

**Comment by evan-gray** [comment]
Upon further review, I feel emitting a wormhole message on redeem is the best thing from a composability perspective and unlocks new possibilities by making a redeem actionable. For example, a project could run a promotion for "redeem our token on Avax and exchange your redemption ticket for an NFT on Eth" 🤤

**Comment by mizdler** [comment]
Maybe it can be VAA driven, so I can decide if I want a receipt (wormhole message) or not (simple event)

**Comment by jumpsiegel** [comment]
I think we should implement this for all chains except solana initially and revisit solana later

**Comment by evan-gray** [comment]
Added in #3173
