### ISSUE TITLE
Update Ganache package

### ISSUE THREAD

**Issue by kev1n-peters** [wormhole-foundation/wormhole#1833]
Wormhole is currently using a deprecated version of [ganache-cli](https://www.npmjs.com/package/ganache-cli). We should upgrade to the [latest ganache version](https://github.com/trufflesuite/ganache/releases/tag/v7.5.0) for its post-merge support. Some features that would be nice are the `finalized` block tag and EIP-1559 (london hard-fork) support.

**Comment by evan-gray** [comment]
Fixed in #3869 by using anvil.
