### ISSUE TITLE
Aptos Governor Limit Increase Proposal

### ISSUE THREAD

**Issue by claudijd** [wormhole-foundation/wormhole#1839]
The current Aptos Governor limit is set to **$1M/$100K**.  This issue is to propose increasing the limit to **$5M/$500K**.

Currently, the natural flow off Aptos is close to exceeding the `dailyLimit` set for Nov 1st.  Additionally, data analysis was done since inception and revealed the following:

- Notional transfers to Aptos peaked around $5M at specific windows of time
- Notional transfers from Aptos peaked around $250K at specific windows of time
- Cumulative Notional Transfer to Aptos is around $45M
- Cumulative Notional Transfer from Aptos is around $4M
- Rolling 1-D notional transfer to Aptos peaked at around $14M in a day
- Rolling 1-D notional transfer from Aptos peaked at around $1M in a day

There are graphs to support the above data, but GitHub issues appear to be preventing the upload of those images for some technical reason.  These will be added once this issue is addressed.  In the interest of these limits having headroom to allow chains to grow over time naturally without being hit during normal operation, the proposal is to increase the limits to **$5M/$500K**.

**Comment by ckeun** [comment]
![image001](https://user-images.githubusercontent.com/5993370/199259407-1837696a-092c-484b-ae28-499a894389ed.png)
![image002](https://user-images.githubusercontent.com/5993370/199259476-43c71780-499a-4e24-81a5-68c912821eac.png)
![image003](https://user-images.githubusercontent.com/5993370/199259492-f4a1caa5-cb7d-4690-8ddf-56f4020a0da3.png)

**Comment by mcf-rocks** [comment]
it's a very new network - you don't think it will be hacked?

**Comment by claudijd** [comment]
@mcf-rocks Sorry I missed this, but as for the Aptos contracts themselves, they have to go through an internal audit and an external audit with no serious issues.  The external audit is published in SECURITY.md at the root of the repo.  The Aptos contracts also have been in pre-release and then full-release eligibility via the $10M bug bounty programs for over a month now, and there have been no serious issues reported.  There is also a second external audit of these smart contract audits, which is also underway now.

On a functional testing front, a good majority of the Aptos smart contracts are also well-designed and unit-tested.  The WH Aptos smart contracts are one of the better implementations in my opinion, but I agree that the L1 is still very new.
