### ISSUE TITLE
Guardian code to generate Batch VAAs

### ISSUE THREAD

**Issue by justinschuldt** [wormhole-foundation/wormhole#1857]
### Overview
As an integrator who composes multiple Wormhole-using contracts, I want to receive an attestation which contains all of the messages with the same nonce emitted in a transaction. Messages could opt-out of a batch by setting a nonce of 0.

### Current Behavior
The only way to compose multiple messages is to submit separate VAAs to the target contract in the same call. Each of these messages would need to be verified separately, adding prohibitive costs. This is also inconvenient to query for / collect from the guardians.

### Proposed Guardian Behavior
All messages will continue to produce a "payload 1" VAA. The guardian will collect messages with a matching non-zero nonce within the same transaction and produce a Batch VAA (payload 2).

### Implementation details
- Define new `BatchVAA` structs that can be marshaled to byte arrays
- Add new gossip protos for p2p messaging
- Add ability for EVM watcher to fetch all message logs from a transaction
- Add state to `Processor` for collecting v1 VAAs by transaction ID
- Ensure `Processor` state cleans up state items to respect memory usage
- Update db.go to store and retrieve BatchVAAs

**Comment by evan-gray** [comment]
Concur with @justinschuldt's comment in #1522 that, at least initially, would be good to shove these code paths behind a feature flag so that these changes can be iterated on and even rolled into a release without needing to be enabled.

**Comment by aadam-10** [comment]
As discussed, this should be modified to reflect the refactor in #1953

**Comment by justinschuldt** [comment]
Here are some things to consider when looking at reference PR [#1522](https://github.com/wormhole-foundation/wormhole/pull/1522), and an update on where this sits:

### implementation details
- Batch VAAs need a different identifier compared to v1 VAAs as messageID is specific to an individual message (unique sequence per message emitted). Batch VAAs are unique to the transaction ID and the nonce. There can be multiple batches from a transaction, messages are grouped into batches by matching nonce. BatchID could be `{emitterChain}:{transactionID}:{nonce}`, where transaction ID is sufficiently long and left-padded, to hold the full IDs from chains like Solana.
    - reference PR [Go SDK structs](https://github.com/wormhole-foundation/wormhole/pull/1522/files#diff-8cfcffc8855dc6d0008d36bc73f1390aa997094e795a932235ea0e5bf49864dfR64) for BatchID. 
- The transaction ID of a batch is not included in the batch's VAA. The transaction ID is included in the gossip messages of batches. Keeping the transaction ID along side the batch VAA is needed, because how else would you index/reference a batch without it, and also for things like the spy, so users/relayers can query for a specific batch VAA.
- The solana transaction hash produced by the solana watcher is not the transaction identifier from the chain. The base58 account ID from Solana is concatenated to fit inside an eth hash [here](https://github.com/wormhole-foundation/wormhole/blob/main/node/pkg/watchers/solana/client.go#L788-L789). The solana watcher will need to be updated to produce a transaction ID that matches the chain's, rather than account ID, or users will have to jump through hoops to translate what they get from the chain to the format produced by the guardian. I made an [issue](https://github.com/wormhole-foundation/wormhole/issues/2364) to track this. Fixing is not needed for the EVM implementation, but should be considered when designing the BatchVAA IDs. 


### Completed:
- BatchVAA gossip message protos. [PR](https://github.com/wormhole-foundation/wormhole/pull/1691/files)
- BatchVAA Go structs, with marshaling/unmarshaling, and signature logic. [PR](https://github.com/wormhole-foundation/wormhole/pull/1700/files), update to separate BatchID from Batch VAA [sdk/vaa/structs.go](https://github.com/wormhole-foundation/wormhole/pull/1522/files#diff-8cfcffc8855dc6d0008d36bc73f1390aa997094e795a932235ea0e5bf49864df)
- Spy integration - watching gossip for batch messages and client subscriptions with filtering. Disabled currently, enable by [adding this](https://github.com/wormhole-foundation/wormhole/pull/1522/files#diff-3572d68a38f54b67f431bd12d6bf81fe2641611a3b659a963a9a861e7668a86fR541). [PR](https://github.com/wormhole-foundation/wormhole/pull/1691/files)


### Needs to be added after Hendrik's guardian refactor [#1953](https://github.com/wormhole-foundation/wormhole/pull/1953):
- Get the source-of-truth about the messages within a transaction. Fetch the messages within a transaction from the chain, so we know when all the individual messages have been signed. This could be very similar to the observation request functionality that currently exists in the guardian.
    - Exists in the reference PR as a `TransactionQuery` which is sent to watchers through a channel `batchReqC` (similar to `obsvReqC`). The resulting data is stored as `TransactionData`. [Reference implementation](https://github.com/wormhole-foundation/wormhole/pull/1522/files#diff-b321171eac1f90e5fb95987f95c0c190357d105821fb445e2e43e7949a698d62R503)
- Create a map of transaction ID to message ID, and another vice versa, so v1 VAAs can be associated with a tx. This is needed because v1 VAAs do not contain info about the transaction. Currently when a message is observed by the guardian a `MessagePublication` holds it's info, and then a subset of the `MessagePublication` becomes the VAA. VAAs that come from gossip have no way of being tied back to a transaction.
    - These maps are stored in [processor state](https://github.com/wormhole-foundation/wormhole/pull/1522/files#diff-294eb6afcd47825254f8bd2931b467eb7ac17498a9c0157b64256327e1305f8cR88) in the reference PR.
- Determine when all of the messages within a TX have reached quorum. for example, when a VAA reaches quorum, check to see if it is part of a batch, and if so, if the batch is now complete (all messages within have a VAA).
    - exists in the reference PR as [node/pkg/processor/batch.go](https://github.com/wormhole-foundation/wormhole/pull/1522/files#diff-d03b83c5004313479139102984f8686f303f7029020af37bcf357e659a31e35a)
- Gossip channels and message handlers for BatchVAA gossip messages.
    - exists in the reference PR in the old style processor ([node/pkg/processor/processor.go](https://github.com/wormhole-foundation/wormhole/pull/1522/files#diff-294eb6afcd47825254f8bd2931b467eb7ac17498a9c0157b64256327e1305f8c)), will need to be updated to work with the new style.
- Once all the messages in the batch have reached quorum, make the BatchVAA, sign it, and broadcast it to gossip. At this point the logic for BatchVAAs is the same as v1 VAAs: collect signatures from peers, check for quorum, broadcast the signed batch VAA when quorum is reached. I imagine a `reactor.NewManager` would be used for this.
- Create a DB prefix for BatchVAAs, indexed by BatchID, and DB handler functions for storing and retriveing them.
    - This can probably be taken wholesale from the reference PR [node/pkg/db/db.go](https://github.com/wormhole-foundation/wormhole/pull/1522/files#diff-a7743499915648ff48f3dbcc56559ebd30096bd20b5119e42c407b64195efe07), should not need modification.
- `publicrpc` endpoint for batch VAAs. Same idea as the endpoint for v1 VAAs, just for batches. Takes a BatchID and returns a BatchVAA.
    - reference PR [node/pkg/publicrpc/publicrpcserver.go](https://github.com/wormhole-foundation/wormhole/pull/1522/files#diff-09af34c899cee25536f4796f31b41d689952ef04fdb5d368279030adc229497eR110), should not need modification.
