### ISSUE TITLE
npm not found in solana-devnet base image

### ISSUE THREAD

**Issue by antonio-altr** [wormhole-foundation/wormhole#1871]
Github issues are **ONLY** for reporting bugs. Before contributing new features (such as a new chain) please first read the [contribution frequently asked questions](https://github.com/wormhole-foundation/wormhole/blob/dev.v2/CONTRIBUTING.md#contributions-faq).

For user support questions such as VAA not found, please use the [Wormhole Official Discord](https://discord.gg/wormholecrypto). Do not give your wallet private key or mnemonic words to anyone.

## Expected Behavior

I'm launching a devnet with a Solana node as described [here](https://github.com/wormhole-foundation/wormhole/blob/dev.v2/DEVELOP.md#local-devnet). Without Solana everything works as expected.

## Current Behavior

With Solana, I get this error:
```
solana-devnet │      [solana  4/14] RUN --mount=type=cache,target=/root/.cache     cargo install --version =2.0.12 --locked spl-token-cli [done: 3m57.492s]
solana-devnet │      [solana  5/14] WORKDIR /usr/src/clients/js
solana-devnet │      [solana  5/14] WORKDIR /usr/src/clients/js [done: 44ms]
solana-devnet │      [solana  6/14] COPY clients/js/package.json clients/js/package-lock.json ./
solana-devnet │      [solana  6/14] COPY clients/js/package.json clients/js/package-lock.json ./ [done: 46ms]
solana-devnet │      [solana  7/14] RUN --mount=type=cache,uid=1000,gid=1000,target=/home/node/.npm     npm ci
solana-devnet │        → /bin/sh: 1: npm: not found
solana-devnet │      
solana-devnet │      ERROR IN: [solana  7/14] RUN --mount=type=cache,uid=1000,gid=1000,target=/home/node/.npm     npm ci
solana-devnet │
solana-devnet │ ERROR: Build Failed: ImageBuild: executor failed running [/bin/sh -c npm ci]: exit code: 127
```

## Possible Solution

That error is for this line: https://github.com/wormhole-foundation/wormhole/blob/51eac5104c1b204b0748cae4abeddec68664ec9e/Dockerfile.client#L14

I think the base image does not have npm so it should be updated.

## Steps to Reproduce

1. `tilt up -- --solana=true`

## Context (Environment)

Issue observed on fresh Ubuntu 20.04 with all the devnet required tools (minikube, Docker, etc) installed.

**Comment by evan-gray** [comment]
Hi @antonio-altr - I wasn't able to reproduce this with latest dev.v2 (https://github.com/wormhole-foundation/wormhole/commit/6de97de242e57be4a0a8a0840f5a16bf4cd55bda) on the following system:

- RHEL8
- x86_64
- Docker 20.10.17
- `minikube start --driver=docker --kubernetes-version=v1.22.3 --cpus=$(nproc) --memory=16G --disk-size=120g --namespace=wormhole`
- Tilt v0.30.5

Could you provide any additional details?

**Comment by aadam-10** [comment]
Please reopen with the information
