### ISSUE TITLE
Script to replay previous transfers and build up initial accounting state

### ISSUE THREAD

**Issue by jynnantonix** [wormhole-foundation/wormhole#1882]

**Comment by justinschuldt** [comment]
You could use BigTable data for this.

**Comment by jynnantonix** [comment]
Yes, that's the plan.  I actually did have a script to do this a couple of months ago but I think I might have deleted it so I have to start over 🤦

**Comment by jynnantonix** [comment]
There is a tool to fetch all tokenbridge VAAs from BigTable here: https://github.com/wormhole-foundation/wormhole/tree/sandbox/jynnantonix/replay/wh

It's unclear if we want to merge the tool into mainline but I'm closing this issue for now because we don't need a separate script for building up transfers now that we can directly submit VAAs to the contract (due to #1884).
