### ISSUE TITLE
Client side tooling for Global accountant

### ISSUE THREAD

**Issue by jynnantonix** [wormhole-foundation/wormhole#1885]
While the normal operation of accounting requires guardians to submit their individual signatures directly on-chain, some methods (`ModifyBalance`, `UpgradeContract`, `Backfill`, etc) require collecting a quorum of signatures *before* submitting the transaction on-chain.

We should have some client side tooling to make it easier for guardians to produce the necessary signatures and to assemble those signatures into a message that can be submitted on-chain.

**Comment by aadam-10** [comment]
This has been addressed as part of other tasks
