### ISSUE TITLE
Certus One guardian seeing buffer overun when writing to bigtable

### ISSUE THREAD

**Issue by bruce-riley** [wormhole-foundation/wormhole#1888]
Looking through the logs, we are seeing quite of few of these errors:

   buffer overrun when attempting to publish message

This indicates that the golang channel used to communicate with the bigtable writer is overflowing. This is most likely due to the increase in PythNet messages. The channel currently has a max size of 50, which is overflowing now that PythNet messages are being published at a rate of 30 per second.

The long term solution is to move the bigtable out of the guardian and have it listen to the gossip network. In the mean time, we should increase the size of this internal channel.

**Comment by kcsongor** [comment]
Aside -- should we change the error text to say that the buffer is full, instead of "buffer overrun" which I think is a technically incorrect term here (and invokes security concerns)?

**Comment by justinschuldt** [comment]
I feel like we should not store PythNet VAAs in BigTable.

We can bail out of the "persist" codepath similar to how we don't save PythNet VAAs to the guardian's internal DB https://github.com/wormhole-foundation/wormhole/pull/1643/files#diff-294eb6afcd47825254f8bd2931b467eb7ac17498a9c0157b64256327e1305f8cR231

I'm going to float this idea to the people who use BigTable data. I can code this up quick, if we want to go this route.

**Comment by justinschuldt** [comment]
> I feel like we should not store PythNet VAAs in BigTable.
> 
> We can bail out of the "persist" codepath similar to how we don't save PythNet VAAs to the guardian's internal DB https://github.com/wormhole-foundation/wormhole/pull/1643/files#diff-294eb6afcd47825254f8bd2931b467eb7ac17498a9c0157b64256327e1305f8cR231
> 
> I'm going to float this idea to the people who use BigTable data. I can code this up quick, if we want to go this route.

We want to continue saving PythNet VAAs to BigTable so their data is included in message volume metrics.
