### ISSUE TITLE
Guardiand changes to route token transfers through accounting before signing

### ISSUE THREAD

**Issue by jynnantonix** [wormhole-foundation/wormhole#1933]
This was previously implemented for the native cosmos module version of accounting in certusone/wormhole-chain-merged#7 so that's a good starting point.

The smart contract version of accounting requires less work on the guardiand side so hopefully it should be a bit easier.  Importantly there's no need for p2p consensus before sending observations to accounting. 

A high-level overview of how this should work is:

* Observe tx on connected chain.
* Check if the emitter address matches the known tokenbridge emitter address and if the tx is a token transfer (i.e. payload 1 or payload 3).
* Sign the observation with the guardian key and send a `SubmitObservations` message to accounting.
* Optional: collect multiple observations and batch them to reduce cosmos tx overhead.  For example, we could collect all the observations received over 1 second and send them all together in a single tx.
* Add a watcher that's listening for events from the accounting smart contract.
* Watch for the "wasm-Transfer" event, which indicates that a quorum of guardians observed the transfer and it was committed to the on-chain state.
* Sign the VAA and broadcast it over the p2p network as normal.
* If the tx is rejected, which should really only happen in the case of insufficient balance, then we need to send an alert to the oncall to investigate.  The PR linked above did this with a discord message.

We may also want to validate a transfer before submitting an observation for it.  This can be done with a new query message, which doesn't exist yet but should be pretty straightforward to implement.

Sub-tasks
----------
- [ ] #2154 
- [ ] #2155

**Comment by jynnantonix** [comment]
I implemented the transfer validation query in #2005.

**Comment by tonyjin** [comment]
Please consider adding this functionality under a feature flag.

**Comment by bruce-riley** [comment]
#2181 implements the guardian changes for this.
