### ISSUE TITLE
Tracking issue for Sui integration - Contracts

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole#1944]
This issue is for grouping core contract related tasks that are necessary for integrating Sui into the Wormhole network.

Other tracking issues:

- https://github.com/wormhole-foundation/wormhole/issues/2354
- https://github.com/wormhole-foundation/wormhole/issues/2353
- https://github.com/wormhole-foundation/wormhole/issues/2443

```[tasklist]
### Task list
- [x] https://github.com/wormhole-foundation/wormhole/issues/1945
- [x] #1947
- [x] #1981
- [x] #1987
- [x] #1972
- [x] #2027
- [x] #1989
- [ ] #2045
- [x] #2011
- [x] #2041
- [x] #2043
- [x] #2054
- [x] #2055
- [x] #2081
- [x] #2291
- [x] #2324
- [x] #2333
- [ ] #2366
- [ ] #2367
- [x] #2368
- [x] #2394
- [x] #2402
- [x] #2404
- [x] #2414
- [x] #2416
- [x] #2429
- [x] #2455
- [ ] #2488
- [ ] #2474
- [ ] #2501
- [ ] #2495
- [ ] #2499
- [ ] #2500
- [ ] #2528
- [ ] #2529
```

**Comment by jumpsiegel** [comment]
[] Sui Guardian/Observation Integration
