### ISSUE TITLE
Polkadot Support

### ISSUE THREAD

**Issue by jamestompson** [wormhole-foundation/wormhole#195]

**Comment by leoluk** [comment]
Wormhole's design is generic and could be extended to Polkadot. Here's what it would take:

1. Find someone willing to fund the development and a team to build it.
2. Convince the current set of Wormhole guardians to run and support a Polkadot node.

**Comment by CryptoUnico** [comment]
> Wormhole's design is generic and could be extended to Polkadot. Here's what it would take:
> 
> 
> 
> 1. Find someone willing to fund the development of a Polkadot port and a team to build it.
> 
> 2. Convince the current set of Wormhole guardians to run and support a Polkadot node.
> 
> 
> 
> I don't know enough about to Polkadot to make a claim about technical feasibility. Wormhole needs a smart contract on the remote side which is capable of verifying secp signatures and mint an SPL token equivalent.

Given the nature of Polkadot as an ecosystem consisting of parachains each with its own set of rules, so long as said rules do not preclude the verification of secp signatures and minting of an SPL token equivalent, then this is theoretically feasible. 

(1) Are these the sole requirements and (2) what constitutes the workload of porting Polkadot? Perhaps an example of an existing port may help make this more concrete.

Your clarification on these matters are appreciated, thank you so much.

**Comment by evan-gray** [comment]
Closing as Polkadot is now supported via Acala and Moonbeam.
