### ISSUE TITLE
sui: Support in SDK

### ISSUE THREAD

**Issue by heyitaki** [wormhole-foundation/wormhole#1964]
Given that Sui is on the Wormhole integration roadmap, the SDK also needs to support Sui.

**Comment by kcsongor** [comment]
How's this progressing @heyitaki ? Is there a branch?

**Comment by heyitaki** [comment]
@kcsongor development is happening via `example-token-bridge-ui` repo; SDK will be formalized and committed here when transfer and attest flows are both working. For now, local development is being blocked by #2019

**Comment by heyitaki** [comment]
Closed by #2830
