### ISSUE TITLE
Can't send native SOL with SDK 0.9.0+

### ISSUE THREAD

**Issue by evan-gray** [wormhole-foundation/wormhole#1965]
## Expected Behavior

`transferNativeSol` should generate and instruction that wraps and transfers native SOL in the token bridge. There should also be an integration test to ensure this works.

## Current Behavior

Trying to call this results in `Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 5: custom program error: 0x1`

## Steps to Reproduce

Attempt to transfer SOL from Solana on the [example token bridge UI](https://wormhole-foundation.github.io/example-token-bridge-ui/#/transfer)

**Comment by kev1n-peters** [comment]
Integration test to reproduce the issue https://github.com/wormhole-foundation/wormhole/commit/98c78c648a4897044ffc408eec68670119a75157

**Comment by virjilakrum** [comment]
<img width="1782" alt="Ekran Resmi 2024-11-07 15 48 09" src="https://github.com/user-attachments/assets/14a12e90-5b68-4b95-9b3c-dfc2d92fb6c4">

`"No instructions found in transaction"`

**How can I solve this error. What I am trying to do is to send hash between two solana wallets with wormhole messaging.**
