### ISSUE TITLE
tilt down doesn't delete resources

### ISSUE THREAD

**Issue by tbjump** [wormhole-foundation/wormhole#1974]
## Expected Behavior

either `tilt down` should delete all resources, or there has to be documentation which command to use instead. 

## Current Behavior

`tilt up -- --ci`
`tilt down`

`kubectl get pods`
NAME                      READY   STATUS    RESTARTS      AGE
aptos-0                   2/2     Running   0             16m
eth-devnet2-0             2/2     Running   2 (23m ago)   24m
guardian-validator-0      1/1     Running   3 (23m ago)   25m
near-0                    2/2     Running   0             33m
redis-0                   1/1     Running   2 (23m ago)   27m
sdk-ci-tests--1-lfq5p     0/1     Running   0             18m
spydk-ci-tests--1-nrqsz   0/1     Running   0             19m
terra-postgres-0          1/1     Running   2 (23m ago)   29m
terra2-postgres-0         1/1     Running   2 (23m ago)   29m

## Possible Solution

`tilt down -- --ci` seems to delete all resources. 
This behavior may have been introduced in https://github.com/wormhole-foundation/wormhole/pull/1795.

**Comment by evan-gray** [comment]
You should `tilt down` with the same resources you did `tilt up`. So, in your case `tilt down -- --ci` should do the trick. https://docs.tilt.dev/cli/tilt_down.html

**Comment by tbjump** [comment]
that's fine, but should we maybe update https://github.com/wormhole-foundation/wormhole/blob/dev.v2/DEVELOP.md then?
