### ISSUE TITLE
Re-observations for transfers stuck in global accountant

### ISSUE THREAD

**Issue by jynnantonix** [wormhole-foundation/wormhole#2002]
Since accounting happens before a VAA is broadcasted over the p2p network we cannot use the existing re-observation infrastructure to unblock transfers that get stuck in accounting waiting for quorum.

However, since we know exactly which signatures are missing we also don't need to spam the entire p2p network for re-observations.  Instead we can have each guardian query the accounting contract for any pending transfers for which it doesn't have an observation from that guardian.  The guardian can then re-observe only those txs and send the observations once it has them.

The proposal is to add a new query method to the accounting contract:

```rust

#[cw_serde]
pub enum QueryMsg {
    /// Query the contract for any pending observations for which it doesn't have an observation
    /// from the provided guardian index.
    #[returns(QueryMissingObservationsResponse)]
    MissingObservations {
        /// The index of the guardian whose signatures we want to check.
        index: u8,
    },
}

#[cw_serde]
pub struct QueryMissingObservationsResponse {
    /// A list of transfers for which the accounting contract does not have an observation from the
    /// requested guardian, along with a list of possible tx_hashes where that transfer may have
    /// occurred.
   missing_observations: Vec<transfer::Key, Vec<Binary>>,
}
```

guardiand would then send this query every (5? 7? 11?) minutes and try to re-observe any missing observations.

**Comment by bruce-riley** [comment]
Here is a proposed design for handling transfers that are stuck in accounting.

# Guardian Accounting Audit Design
The audit will run periodically, say every ten minutes. It will consist of two phases performed back-to-back.

## Phase 1: Transfers the contract has in the pending state
- Issue the **AllPendingTransfers** query to the contract.
- Loop through the results.
  - If the transfer is in our pending map:
    - Validate that the digest matches. If not, peg a critical error and skip it. **Not sure how to recover from this!**
    - Update our timestamp.
    - If we are not marked as having signed it, resend the observation to the contract.
    - Otherwise continue waiting for it to reach quorum.
  - If the transfer is not in our pending map, submit a reobservation request to the **obsvReqC** channel.

## Phase 2: Transfers that we have in the pending state but the contract does not
Phase 2 covers a couple of infrequent scenarios:
- We previously failed to send an observation request to the contract.
- We missed the WasmTransfer event published by the contract.

Phase two involves looping through our pending map and doing the following:
  - If the timestamp indicates it has been idle too long (also meaning it wasn't handled in phase 1):
    - Update our timestamp.
    - Resubmit the observation to the contract. If the transfer has already been committed or rejected,
      that will be handled by the existing code.

## Notes:
The **NewAccounting()** method will need to take the **obsvReqC** parameter from node.go.

By submitting the reobservation request to the **obsvReqC** channel, it will be throttled if necessary. 

We need to handle pagnated results from the **AllPendingTransfers** query.

**Comment by jynnantonix** [comment]
Going to quote and comment inline:

> Here is a proposed design for handling transfers that are stuck in accounting.
> 
> # Guardiand Accounting Audit Design
> The audit will run periodically, say every ten minutes. It will consist of two phases performed back-to-back.
> 
> ## Phase 1: Verify transfers the contract has in the pending state
> * Issue the **AllPendingTransfers** query to the contract.
> * Loop through the results.
>   
>   * If the transfer is in our pending map:
>     
>     * Validate that the digest matches. If not, peg a critical error and skip it. **Not sure how to recover from this!**

I don't think digest mismatches should be an error while a transfer is pending.  These could happen because of a fork or rollback.  In fact, the **AllPendingTransfers** query can return multiple observations for the same `(emitter_chain, emitter_address, sequence)` tuple so this code would have to handle that.

I think digest mismatches should only be an error if we have quorum.

>     * Update our timestamp.
>     * If we are not marked as having signed it, resend the observation to the contract.

This can be done more easily via the `MissingObservations` query.

>     * Otherwise continue waiting for it to reach quorum.
>   * If the transfer is not in our pending map, submit a reobservation request to the **obsvReqC** channel.

This can also be done more easily via the `MissingObservations` query.

> 
> ## Phase 2: Verify transfers that guardiand has in the pending state but the contract does not
> Phase 2 covers a couple of infrequent scenarios:
> 
> * We previously failed to send an observation request to the contract.
> * We missed the WasmTransfer event published by the contract.
> 
> Phase two involves looping through our pending map and doing the following:
> 
> * If the timestamp indicates it has been idle too long (also meaning it wasn't handled in phase 1):
>   
>   * Update our timestamp.
>   * Resubmit the observation to the contract. If the transfer has already been committed or rejected, that will be handled by the existing code.

Blindly resubmitting like this is going to spam the network unnecessarily.  We have the mechanism to do more targeted resubmissions so we should use it.


I suggest the following alternative that runs every audit interval:

  * Loop through the pending map and create a new map of `(chain_id, tx_hash)` pairs to `Observation`s.  Making a separate map means we don't need to hold the lock on the pending map while doing the audit so we could even do the remaining steps in a separate goroutine to avoid blocking the main loop.
  * Issue the `MissingObservations` query to the contract.
  * For each missing observation in the response:
    * Check if the `(chain_id, tx_hash)` pair exists in the map we created in step 1.
      * If the pair exists, that means we previously failed to send the observation to the contract so resubmit it.  Then remove the entry from the map.
      * If the pair does not exist, submit a reobservation request to the watcher.
  * For each entry remaining in the map from step 1:
    * Issue the `Transfer` query to the contract.  This will check if the transfer was already committed and we missed the event.
    * If the `Transfer` query returns failure, the transfer has not yet committed so skip it.
    * If the `Transfer` query returns success, validate that the digest matches.  If not, log an error and skip.
    * Delete the entry from the pending map and publish the transfer.

**Comment by bruce-riley** [comment]
@jynnantonix , one question about your proposal. In phase 2, what if the transfer has been rejected (insufficient balance)? Will the transfer query tell me that?

**Comment by jynnantonix** [comment]
No, for that we'd need to parse the payload and then send a `ValidateTransfer` query, which will then check the transfer details.

**Comment by bruce-riley** [comment]
@jynnantonix and I discussed this in more detail and came up with the following design.

The audit will submit the `MissingObservations` query and process it as described above.

If there are any transfers left in the temporary map, rather than submitting a bunch of individual queries, the new `TransferStatus` query will be used to request the status of all transfers still in the temporary map in a single query. That will tell us if each transfer is committed, pending or unknown.

If a transfer is marked as unknown, that may mean that it was rejected due to insufficient balance. We should be able to use the ValidateTransfer query to see if that is the case. If that does not work, we may need to have the guardians gossip insufficient balance errors since only the guardian who reaches quorum would see it directly.

The `TransferStatus` query is being added by PR #2229.
