### ISSUE TITLE
Validate initial accounting state with on-chain balances

### ISSUE THREAD

**Issue by jynnantonix** [wormhole-foundation/wormhole#2003]
Once #1882 is fixed we want to ensure that the on-chain accounting state matches the token balances in each tokenbridge contract.

Once we pick a snapshot time, we should query the full list of token balances locked in each tokenbridge contract.  Then once we've finished replaying the transfers we can compare the two sets of token balances and make sure that they match.

Adding @ckeun @evan-gray if they're aware of something we might already have to fetch token balances from all the tokenbridge contracts.

**Comment by ckeun** [comment]
Yes! We've got some scripts to pull on-chain contract token balances. But it relies on having a list of token addresses, which currently is either the allowlist or a token list pulled from covalent (covers only a subset of chains, mostly evm).
