### ISSUE TITLE
Additional negative test coverage for global accountant

### ISSUE THREAD

**Issue by jynnantonix** [wormhole-foundation/wormhole#2004]
The accounting code has several negative unit and integration tests but it would be nice to also have some "real life" negative tests.

One test is to ensure that the hack from February gets blocked when we're replaying all the previous transfers for #1882.

Other options are to add negative tests to tilt or testnet (or both).  In both cases we would need to forge a fake VAA to emit a bunch of unbacked wrapped tokens and then try to send those back to their native chain.  The test would be successful if accounting blocks the transfer.

Doing this in tilt will likely be quicker to implement than doing it in testnet because testnet would require a testnet wormchain, testnet tokenbridge on wormchain, and testnet accounting, which is a lot of infra that we don't currently have.

**Comment by tonyjin** [comment]
Resolved by #2314
