### ISSUE TITLE
worm CLI shouldn't be packaged in Aptos Docker image

### ISSUE THREAD

**Issue by heyitaki** [wormhole-foundation/wormhole#2026]
As the title suggests, worm CLI should be built in CI as opposed to pre-built in the base image to propagate updates to CLI without requiring another publish of the base image. 

This issue is blocking #1990 because it changes the airdrop amount in `worm aptos faucet`, but the change is not being picked up in CI as the base image does not have the `worm` update.

**Comment by evan-gray** [comment]
Relates to #2157
