### ISSUE TITLE
Make tilt ci tests faster

### ISSUE THREAD

**Issue by tbjump** [wormhole-foundation/wormhole#2029]
A local run of `tilt ci -- --ci` took ~20m based on branch `tbjump/t2`. 

Can we make it faster? 

Bottleneck:
const-gen
solana-devnet
    build solana-contract: 348.86s
    build bridge-client: 351.54s
    solana-devnet pod ready: 23s
guardian: ~30s
spy: ~30s
sdk-ci-tests: 11m

# Job runtimes
NAME             COMPLETIONS   DURATION
eth-deploy       1/1           2m45s
eth-deploy2      1/1           2m35s
near-deploy      1/1           111s
sdk-ci-tests     1/1           11m
spydk-ci-tests   1/1           11m

# image build times
eth-node: 27.49s
near-node: 114.08s
near-deploy: 192.72s
redis: 111.77s
spy-relayer: 70.39s
terra-contracts: 638.80s
terra2-contracts: 634.47s
wormchaind-image: 204.84s
solana-contract: 348.86s
bridge-client: 351.54s

# Pod ready times:
eth-devnet: 27.26s
eth-devnet2: 27s
guardian: 21s
redis: 24s
spy: 22s
near: 22s
spy-listener: 22s
spy-relayer: 21s
spy-wallet-monitor: 21s
terra-terrad: 32s
solana-devnet: 23s

**Comment by evan-gray** [comment]
Happy to review specific bottlenecks and ideas to speed up. Closing since as written it's not very actionable. These also only take ~7m in CI
