### ISSUE TITLE
sui: consider hardcoding constants like `chain_id`

### ISSUE THREAD

**Issue by kcsongor** [wormhole-foundation/wormhole#2041]
Currently, there are several fields in https://github.com/wormhole-foundation/wormhole/blob/58cd4ec81e976d67fcbeb9b1f97fb44fc6599847/sui/wormhole/sources/state.move#L34-L63

that don't really ever change, and even if they did, they would require contract upgrades anyway. These are `chain_id`, `governance_chain_id`, and `governance_contract`. The fact that they are part of the state means that accessing them now requires the `State` object to be passed to the transaction, as in:

https://github.com/wormhole-foundation/wormhole/blob/58cd4ec81e976d67fcbeb9b1f97fb44fc6599847/sui/token_bridge/sources/bridge_state.move#L327-L331

Proposal: we should just hardcode these values in the relevant getter functions, so
```rust
    public fun get_chain_id(state: &State): U16 {
        return state.chain_id
    }
```
would become
```rust
    public fun get_chain_id(): U16 {
        return 21
    }
```

**Comment by kcsongor** [comment]
@optke3 what are your thoughts?

**Comment by optke3** [comment]
I'm on board with this.

**Comment by aadam-10** [comment]
already done elsewhere
