### ISSUE TITLE
sui: add tests for `attest_token`

### ISSUE THREAD

**Issue by kcsongor** [wormhole-foundation/wormhole#2042]
We should adapt the tests from the aptos contract
https://github.com/wormhole-foundation/wormhole/blob/58cd4ec81e976d67fcbeb9b1f97fb44fc6599847/aptos/token_bridge/sources/attest_token.move#L60-L143

**Comment by optke3** [comment]
Relevant branch: https://github.com/wormhole-foundation/wormhole/tree/sui/token_bridge_attestation

**Comment by optke3** [comment]
PR: https://github.com/wormhole-foundation/wormhole/pull/2204
