### ISSUE TITLE
sui: add `README.md` with hacking instructions

### ISSUE THREAD

**Issue by kcsongor** [wormhole-foundation/wormhole#2046]
For aptos, we have a README that includes detailed instructions on how to set up a local development environment. https://github.com/wormhole-foundation/wormhole/blob/58cd4ec81e976d67fcbeb9b1f97fb44fc6599847/aptos/README.md

We should have the same for sui

**Comment by aadam-10** [comment]
duplicates https://github.com/wormhole-foundation/wormhole/issues/2363
