### ISSUE TITLE
sui: test guardian set expiry

### ISSUE THREAD

**Issue by kcsongor** [wormhole-foundation/wormhole#2050]
We should port this test from aptos: https://github.com/wormhole-foundation/wormhole/blob/9acf17f6e0a2a4c8fefc00425a8bb5686685f74c/aptos/wormhole/sources/guardian_set_upgrade.move#L146-L176

Since the sui runtime doesn't expose timestamp information, only epochs, these tests might uncover some bugs in the implementation. The https://github.com/MystenLabs/sui/blob/760d8ef08d4e320a24aebcc5b12c5d9596b17df8/crates/sui-framework/sources/tx_context.move#L118-L121 function will come in handy in implementing these tests.

**Comment by optke3** [comment]
Relevant PR: https://github.com/wormhole-foundation/wormhole/pull/2079
