### ISSUE TITLE
sui: ensure contracts are up to date with aptos

### ISSUE THREAD

**Issue by kcsongor** [wormhole-foundation/wormhole#2054]
The sui contract development started off from an outdated version of the aptos contracts (from the `aptos/integration branch, instead of `main`), so we should make sure that everything is up to date before we call the contracts final.

Some things that come to mind:
- [x] `submit_vaa_entry` functions accompany the `submit_vaa` functions which are meant for being called as entry
- [x] rename `bridge_state` -> `bridge`
- [x] `complete_transfer` is incomplete and tests are outdated

**Comment by optke3** [comment]
Do you mean `BridgeState` -> `State`?

**Comment by optke3** [comment]
Relevant branch for  updated `complete_transfer` tests: https://github.com/wormhole-foundation/wormhole/tree/sui/update_contracts_compare_aptos

**Comment by optke3** [comment]
PR for `complete_transfer`: https://github.com/wormhole-foundation/wormhole/pull/2217

**Comment by aadam-10** [comment]
the first two items should be discussed with @kcsongor
