### ISSUE TITLE
sui: store message fee coins in the contract state shared object

### ISSUE THREAD

**Issue by kcsongor** [wormhole-foundation/wormhole#2081]
Currently in `wormhole::publish_message` we transfer ownership of the `message_fee` coins to `@wormhole`, which is the deployer address. This is not great, because we want the deployer to have no special permissions beyond deploying the contract, and definitely no access to message fees.

So instead of transferring the coins to the wormhole address, we should move these coins into the shared `State` object of the wormhole contract. This struct is gated by functionality exposed through the wormhole modules, so we can add a governance method to then withdraw the funds later.

**Comment by optke3** [comment]
Seems like on Aptos, the coins are deposited directly to the @wormhole account: https://github.com/wormhole-foundation/wormhole/blob/main/aptos/wormhole/sources/wormhole.move#L30

Is this something we'd like to modify?
