### ISSUE TITLE
aptos NFT bridge unit tests

### ISSUE THREAD

**Issue by jumpsiegel** [wormhole-foundation/wormhole#2113]

**Comment by kcsongor** [comment]
is this for the nft bridge?

**Comment by optke3** [comment]
Test for create wrapped collection: https://github.com/wormhole-foundation/wormhole/pull/2116

**Comment by optke3** [comment]
There seems to be a few issues with the existing implementation of Aptos NFT Bridge - minting a new token is not possible without first doing token::create_tokendata and setting properties like burnability, etc. 

Working on fixes and adding more tests!

**Comment by optke3** [comment]
New PR here: https://github.com/wormhole-foundation/wormhole/pull/2126
