### ISSUE TITLE
Can libp2p lose connectivity to all peers?

### ISSUE THREAD

**Issue by leoluk** [wormhole-foundation/wormhole#218]
A guardian node lost gossip connectivity after a network outage:

> Jul 18 06:25:15 wormhole guardiand[17131]: 2021-07-18T06:25:15.621+0300#011#033[33mWARN#033[0m#011dht/RtRefreshManager#011failed when refreshing routing table#011{"error": "2 errors occurred:\n\t* failed to query for self, err=failed to find any peer in table\n\t* failed to refresh cpl=0, err=failed to find any peer in table\n\n"}

There's no libp2p errors that would explain why this occurred. A restart fixed it. One theory is libp2p eventually giving up on dialing all known peers, including the seed node - in which case the fix would be a background routing attempting to reconnect to the seed every once in a while. We need to reproduce this in a devnet with DEBUG log level.

**Comment by aadam-10** [comment]
@kev1n-peters can you check if was this fixed?

**Comment by kev1n-peters** [comment]
This was fixed in https://github.com/wormhole-foundation/wormhole/pull/1455
