### ISSUE TITLE
Register Oasis & Acala bridge contract on BSC in testnet

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole#2182]
To unblock an integrator, please register Oasis & Acala bridge contract info on BSC in testnet.

**Comment by bruce-riley** [comment]
Updated the registrations for Oasis and Acala on BSC testnet.

`$ worm evm info -c bsc -n testnet -m TokenBridge
WARNING: 'worm' is out of date. Run 'worm update' to update.
{
  "address": "0x9dcF9D205C9De35334D646BeE44b2D2859712A09",
  "wormhole": "0x68605AD7b15c732a30b1BbC62BE8F2A509D74b4D",
  "implementation": "0x4B8FBCd6f9462DE5FBdC244d9b89275ceBBA8e32",
  "isInitialized": true,
  "tokenImplementation": "0x4e3a68a43C37d9d3DB145D43455075037293c591",
  "chainId": 4,
  "finality": 15,
  "evmChainId": "97",
  "isFork": false,
  "governanceChainId": 1,
  "governanceContract": "0x0000000000000000000000000000000000000000000000000000000000000004",
  "WETH": "0xae13d989daC2f0dEbFf460aC112a837C89BAa7cd",
  "registrations": {
    "solana": "0x3b26409f8aaded3f5ddca184695aa6a0fa829b0c85caf84856324896d214ca98",
    "ethereum": "0x000000000000000000000000f890982f9310df57d00f659cf4fd87e65aded8d7",
    "terra": "0x0000000000000000000000000c32d68d8f22613f6b9511872dad35a59bfdf7f0",
    "polygon": "0x000000000000000000000000377d55a7928c046e18eebb61977e714d2a76472a",
    "avalanche": "0x00000000000000000000000061e44e506ca5659e6c0bba9b678586fa2d729756",
    "oasis": "0x00000000000000000000000088d8004a9bdbfd9d28090a02010c19897a29605c",
    "algorand": "0x6241ffdc032b693bfb8544858f0403dec86f2e1720af9f34f8d65fe574b6238c",
    "aurora": "0x000000000000000000000000d05ed3ad637b890d68a854d607eeaf11af456fba",
    "fantom": "0x000000000000000000000000599cea2204b4faecd584ab1f2b6aca137a0afbe8",
    "karura": "0x000000000000000000000000d11de1f930ea1f7dd0290fe3a2e35b9c91aefb37",
    "acala": "0x000000000000000000000000eba00cbe08992edd08ed7793e07ad6063c807004",
    "klaytn": "0x000000000000000000000000c7a13be098720840dea132d860fdfa030884b09a",
    "celo": "0x00000000000000000000000005ca6037ec51f8b712ed2e6fa72219feae74e153",
    "near": "0xc2c0b6ecbbe9ecf91b2b7999f0264018ba68126c2e83bf413f59f712f3a1df55",
    "moonbeam": "0x000000000000000000000000bc976d4b9d57e57c3ca52e1fd136c45ff7955a96",
    "neon": "0x000000000000000000000000ee3db83916ccdc3593b734f7f2d16d630f39f1d0",
    "terra2": "0xc3d4c6c2bcba163de1defb7e8f505cdb40619eee4fa618678955e8790ae1448d",
    "injective": "0x00000000000000000000000003f3e7b2e363f51cf6e57ef85f43a2b91dbce501",
    "osmosis": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "sui": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "aptos": "0x0000000000000000000000000000000000000000000000000000000000000001",
    "arbitrum": "0x00000000000000000000000023908a62110e21c04f3a4e011d24f901f911744a",
    "optimism": "0x000000000000000000000000c7a204bdbfe983fcd8d8e61d02b475d4073ff97e",
    "gnosis": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "pythnet": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "xpla": "0xb66da121bd3621c8d2604c08c82965640fe682d606af26a302ee09094f5e62cf",
    "wormchain": "0x0000000000000000000000000000000000000000000000000000000000000000"
  }
}
$ worm evm info -c bsc -n testnet -m NFTBridge
WARNING: 'worm' is out of date. Run 'worm update' to update.
{
  "address": "0xcD16E5613EF35599dc82B24Cb45B5A93D779f1EE",
  "wormhole": "0x68605AD7b15c732a30b1BbC62BE8F2A509D74b4D",
  "implementation": "0x56E182615D87ADAB661fb899f92566Da75D7823e",
  "isInitialized": true,
  "tokenImplementation": "0x776CBa10EdBf5664d3d988E5506637e97CfA4bcf",
  "chainId": 4,
  "finality": 15,
  "evmChainId": "97",
  "isFork": false,
  "governanceChainId": 1,
  "governanceContract": "0x0000000000000000000000000000000000000000000000000000000000000004",
  "registrations": {
    "solana": "0x752a49814e40b96b097207e4b53fdd330544e1e661653fbad4bc159cc28a839e",
    "ethereum": "0x000000000000000000000000d8e4c2dbdd2e2bd8f1336ea691dbff6952b1a6eb",
    "terra": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "polygon": "0x00000000000000000000000051a02d0dcb5e52f5b92bdaa38fa013c91c7309a9",
    "avalanche": "0x000000000000000000000000d601baf2eee3c028344471684f6b27e789d9075d",
    "oasis": "0x000000000000000000000000c5c25b41ab0b797571620f5204afa116a44c0eba",
    "algorand": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "aurora": "0x0000000000000000000000008f399607e9ba2405d87f5f3e1b78d950b44b2e24",
    "fantom": "0x00000000000000000000000063ed9318628d26bdcb15df58b53bb27231d1b227",
    "karura": "0x0000000000000000000000000a693c2d594292b6eb89cb50efe4b0b63dd2760d",
    "acala": "0x00000000000000000000000096f1335e0acab3cfd9899b30b2374e25a2148a6e",
    "klaytn": "0x00000000000000000000000094c994fc51c13101062958b567e743f1a04432de",
    "celo": "0x000000000000000000000000acd8190f647a31e56a656748bc30f69259f245db",
    "near": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "moonbeam": "0x00000000000000000000000098a0f4b96972b32fcb3bd03caeb66a44a6ab9edb",
    "neon": "0x00000000000000000000000066e5bcfd45d2f3f166c567ada663f9d2ffb292b4",
    "terra2": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "injective": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "osmosis": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "sui": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "aptos": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "arbitrum": "0x000000000000000000000000ee3db83916ccdc3593b734f7f2d16d630f39f1d0",
    "optimism": "0x00000000000000000000000023908a62110e21c04f3a4e011d24f901f911744a",
    "gnosis": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "pythnet": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "xpla": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "wormchain": "0x0000000000000000000000000000000000000000000000000000000000000000"
  }
}
$`
