### ISSUE TITLE
Guardian accounting interface should batch requests

### ISSUE THREAD

**Issue by bruce-riley** [wormhole-foundation/wormhole#2188]
+1, if multiple tx's are submitted in parallel, there will be sequence number collisions.

However, only submitting 1 message per 1 tx per 1 block I think will run into a bottleneck pretty quickly.

I think we'll need to submit a variable number of messages per tx.  So the new goroutine should consume up to ~100-200 messages at a time from the channel and submit them in a single tx per block.
Multiple observations/messages can be included here in the TX:
https://github.com/wormhole-foundation/wormhole/blob/9fe03b07b27f894d95d4e8cbefb0660046272964/node/pkg/wormconn/send_tx.go#L37

This could make error handling more tricky.  If one of the messages gets an error, I believe the whole tx will be rejected.

_Originally posted by @conorpp in https://github.com/wormhole-foundation/wormhole/pull/2181#discussion_r1060718754_

**Comment by conorpp** [comment]
Just to update -- there are multiple observations submitted in a single tx, so I think the current 1 tx per block is fine.  The optimization could just be:
1. Read all messages from channel. 
2. Create new message containing observations of input messages, and submit the new message instead.
