### ISSUE TITLE
Add Modified Token Bridge to Wormchain

### ISSUE THREAD

**Issue by nik-suri** [wormhole-foundation/wormhole#2196]
Eventually, we will need to add the token bridge to wormchain to support bridging tokens directly to wormchain.

Whenever this happens, we should deploy a modified version of the cosmwasm token bridge contract that calls into wormchain instead of the core bridge contract for core functionality. Wormchain already implements the core functionality and stores the current guardian set, so using this method will let us avoid having to update the guardian set in two places on wormchain (wormchain itself and the core bridge contract).

This functionality should be enabled by using a compile-time feature flag.

Specifically, we should edit all instances where we post wormhole messages like this - https://github.com/wormhole-foundation/wormhole/blob/main/cosmwasm/contracts/token-bridge/src/contract.rs#L212-L219 - to call into the wormchain `PostMessage` function - https://github.com/wormhole-foundation/wormhole/blob/main/wormchain/x/wormhole/keeper/emitter.go#L10.

**Comment by aadam-10** [comment]
closing as no longer relevant according to @conorpp
