### ISSUE TITLE
Update Core Bridge Cosmwasm contract to publish IBC Message to wormchain

### ISSUE THREAD

**Issue by nik-suri** [wormhole-foundation/wormhole#2198]
Edit the `publishMessage` function to send an IBC message to wormchain instead of directly emitting a wormhole message on the source chain.

This functionality should ideally be enabled using a compile-time feature flag.

**Comment by jynnantonix** [comment]
Unfortunately there's no way to properly do mutually exclusive compile time features in rust in a single crate.  Cargo features are [supposed to be additive](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification):

> A consequence of this is that features should be additive. That is, enabling a feature should not disable functionality, and it should usually be safe to enable any combination of features.

If we want to do this the Right Way (TM) then I think we should have a new "wormhole-ibc" contract that depends on the original core bridge as a library, delegates all the handling to the original core bridge, and then converts any attributes and events from the `Response` struct into IBC messages that get posted to wormchain.

See the various *-shutdown contracts for examples where we've done something similar.
