### ISSUE TITLE
Wormchain - token bridge without wormhole core contract

### ISSUE THREAD

**Issue by justinschuldt** [wormhole-foundation/wormhole#2275]
The cosmwasm token bridge contract requires wormhole core contract be deployed and initialized, so it can read the guardian set, etc.
Wormchain uses a native module to hold the guardian set, in order to use with cosmos consensus config (registering validator key on behalf of a guardian).

In order to deploy the token bridge to wormchain without the wormhole core, we'll need to modify the token bridge to reference wormchain's guardian set info.

We'll need to use these [bindings](https://github.com/wormhole-foundation/wormhole/issues/1881), the work will be similar to what was done for the accountant contract (https://github.com/wormhole-foundation/wormhole/issues/2103).

**Comment by justinschuldt** [comment]
FYI @jynnantonix, feel free to edit

**Comment by aadam-10** [comment]
closing as no longer relevant according to @conorpp
