### ISSUE TITLE
Acct: Guardian support for modification governance

### ISSUE THREAD

**Issue by evan-gray** [wormhole-foundation/wormhole#2327]
## Expected Behavior

The guardian should be able to produce a signature for the modification command. Though maybe this should be a VAA (so that it can get gossiped, otherwise I'm not quite sure how to accumulate them). https://github.com/wormhole-foundation/wormhole/blob/main/cosmwasm/contracts/global-accountant/src/contract.rs#L298-L331

## Current Behavior

I'm not sure there's a way to actually make one of these in production.

**Comment by aadam-10** [comment]
https://github.com/wormhole-foundation/wormhole/pull/2371
