### ISSUE TITLE
I think there is a typo in the docs "trasnfer"instead of "transfer"

### ISSUE THREAD

**Issue by ForestLionFoccacia** [wormhole-foundation/wormhole#2330]
https://docs.wormhole.com/wormhole/portal-examples/evm-to-solana

<img width="809" alt="image" src="https://user-images.githubusercontent.com/96025490/216216915-8be0677d-f8db-4c95-9d15-4fd92c436b69.png">

**Comment by evan-gray** [comment]
Thank you! Fixed 🙂
