### ISSUE TITLE
VAA Guardians Expiring causing token to be locked in bridge forever

### ISSUE THREAD

**Issue by wasif28** [wormhole-foundation/wormhole#2331]
Im using the wormhole ICCO and whenever I try to initSale using the VAA I get an error,
The VAA was generated earlier before the guardians were updated on the core wormhole bridge
It is also not possible for me to regenerate the message but I want to use the existing VAA

## Expected Behavior

This should be making sure that VAA's which are not replayable should have no time limit of expiry and older guardians should be compatible for already generated VAA's that were never used

## Current Behavior

I am getting this error 
"execution reverted: guardian set has expired"
I also know that the guardians were changed on the core contracts that may be the issues root cause

## Possible Solution

Make sure that previous VAA's are not expirable and when guardians are renewed previous VAA's still work but newer messages are only signed by new guardian sets and previous VAA's should work.

## Steps to Reproduce

conductor AVAX: 0xac8E86FEeeEF1E9996acd1115f6d1b796a9518C6
contributor FTM: 0xac8E86FEeeEF1E9996acd1115f6d1b796a9518C6
contributor POLYGON tx already done: 0xae407a45807ed04902b4345de9162d39957a1b61cf5df2231e8e4048c92e3cf7

VAA: 0x01000000020d02add37926515c2a16120860299ba64a163836d5af1da5889728ce8759f7d840d42bb7215260ad7942f343805ed8a7d68729fb6d4e5979c90a0d5830c6ec97207200046f7a60de2e302ee748c922525f12cbf337d1633e48593f133e2da595ee0e0ba568abe7c02ee05d30ce92bc54f12d30323560a280670ba7cd7b65e2c8f5aef2e901053a8dc0c9c67903c46f8ebd44a4a49764297eee77b3ab00638a38e4ef1c0e850a2576835d7c103a9457319c0a2019b646288da0831326995008c62e76fec1c70101071df0a971d9cc21cd409ee7ef5ad184d1ed3d54046f5f8faff551ef6f71b08e6935b9a8e52546253c6b8897f5d06beb503bbb199ac2373b0f20c64896946c74e50008814ae3f939137f0afc9383b0688201ef43758b500463e99faaf5d9278ee4bb0f01df98498bb4c1bb2ca333e9e0a756650240a4db0881c3980563dd07891467ac00092851076fdb6f17610afa58f0828399d20615be2062270d8ca13d5aa2913adb9041cbc3aae5b987625b5d4e9ace5e147ac845d585cc29905848642019c061f4fa000a137820b1671ac905c40419e39c53db499bf99a547b964de2de57a0d04eb3c8a87e559c1e3853214437589c7fc2e2889bef74dfb613214deccccf154ac7398655000b2de0e1759ea0e0c9fcab076c821a3c6d1c35b4712c3ecf22b2bb86ba747f215d354fa1df31c66a382ab3eeeb3d272e5443804586dbd9a39fc75395968470bd5e000cc009e9a780bd18122a1f6bf7d1e9239905b087933fd9680f2bd54e6267df87527987bd7e7fe812312d6a9777608837d813fae2b395d67d2632b7cce67510deaf010d142007cd3c2e7f45c2a68630dc98c88b930ae8d78763fd2956b456e08057369003ae55941eac57cdf202db204e9844f1a11a72f96b648bd892d33242a992744e000fb7b29c716ec9a73fd6eeb1601f44713dac1f3927320f5a297ec9bad709eb66165d0895a78aad3105919bb5e6dc2f00b76129e82033e14fa2e9a2dbbbb1daa53d01105f6b3e97823582e385e62199fcefc760f8ddbde0ba88e681a4a8eee5763d43e71d5f3fdc93f1c3938f5a2e4993473574174b92d34bddb396362d9a1e8266fb9c0011cbb397d7a1c8abd0a01d3aa02445c70e916c26df4eb06ea3bc3ab4920eba139e60cc77409a7b2b002b95aab58a01ef25765e4651471bc9ec83f06e31b398cd890063639779000000000006000000000000000000000000ac8e86feeeef1e9996acd1115f6d1b796a9518c600000000000000220f01000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000007168518585d5bf16f62fefb346f365120738c4b0000612000000000000000000000000000000000000000000000000000000006363a890000000000000000000000000000000000000000000000000000000006363ba2404000000000000000000000000b97ef9ef8734c71904d8002f8b6bc66dd9c48a6e00060000000000000000000000e8d4a51000c6fa7af3bedbad3a3d65f36aabc97431b1bbe4c2d2f6e0e47ca60203452f5d6100010000000000000000000000e8d4a5100000000000000000000000000004068da6c83afcfa0e13ba15a6696662335d5b75000a0000000000000000000000e8d4a510000000000000000000000000002791bca1f2de4661ed88a30c99a7a9449aa8417400050000000000000000000000e8d4a51000000000000000000000000000870dc16249b860af63d671e02966b82ff44ac0a6eb15d7699592e1d8ddab0073499b17c515ad0630000000000000000000000000000000000000000000000000000000006363c258

1) load the contract of icco contributor on remix using this address 0xac8E86FEeeEF1E9996acd1115f6d1b796a9518C6
2) when we initSale on ICCO contributor on FTM chain using the provided VAA we can get the error.

**Comment by evan-gray** [comment]
Hi! The guardian set expiry is a safety mechanism, as you don’t want a guardian key no longer in the set to be able to sign new messages! However, there is a `repairVAA` method in the SDK which can determine if a VAA is valid for the current guardian set. Additionally, I have requested that the latest guardian, xLabs, re-sign all messages so that they are available with the latest guardian set. I can check if either of these check out for the VAA you posted shortly.

**Comment by evan-gray** [comment]
Hi @wasif28 , this one should work for you. Same VAA but with guardian set 3 and xLabs signature. We can make more of these available somewhere if you need.

```
01000000030d012dd115f1c45b90ead748002f2b66c359331e78481e27780b2738ad7e3c47b5d628cebaba4fd5f6e969efda535129c3953a7b45f2d4a6e926342a7c77e4edf2140002add37926515c2a16120860299ba64a163836d5af1da5889728ce8759f7d840d42bb7215260ad7942f343805ed8a7d68729fb6d4e5979c90a0d5830c6ec97207200053a8dc0c9c67903c46f8ebd44a4a49764297eee77b3ab00638a38e4ef1c0e850a2576835d7c103a9457319c0a2019b646288da0831326995008c62e76fec1c7010107598db8deb67a96becbdf95aea7b03f131a5da9779878d4bd51c9af27b97379634e8c71ee7a0b3a048c62a306895f317b5225ae3b99a3c32485223ec056d173450108814ae3f939137f0afc9383b0688201ef43758b500463e99faaf5d9278ee4bb0f01df98498bb4c1bb2ca333e9e0a756650240a4db0881c3980563dd07891467ac00092851076fdb6f17610afa58f0828399d20615be2062270d8ca13d5aa2913adb9041cbc3aae5b987625b5d4e9ace5e147ac845d585cc29905848642019c061f4fa000a137820b1671ac905c40419e39c53db499bf99a547b964de2de57a0d04eb3c8a87e559c1e3853214437589c7fc2e2889bef74dfb613214deccccf154ac7398655000b2de0e1759ea0e0c9fcab076c821a3c6d1c35b4712c3ecf22b2bb86ba747f215d354fa1df31c66a382ab3eeeb3d272e5443804586dbd9a39fc75395968470bd5e000cc009e9a780bd18122a1f6bf7d1e9239905b087933fd9680f2bd54e6267df87527987bd7e7fe812312d6a9777608837d813fae2b395d67d2632b7cce67510deaf010d142007cd3c2e7f45c2a68630dc98c88b930ae8d78763fd2956b456e08057369003ae55941eac57cdf202db204e9844f1a11a72f96b648bd892d33242a992744e000fb7b29c716ec9a73fd6eeb1601f44713dac1f3927320f5a297ec9bad709eb66165d0895a78aad3105919bb5e6dc2f00b76129e82033e14fa2e9a2dbbbb1daa53d01105f6b3e97823582e385e62199fcefc760f8ddbde0ba88e681a4a8eee5763d43e71d5f3fdc93f1c3938f5a2e4993473574174b92d34bddb396362d9a1e8266fb9c0011cbb397d7a1c8abd0a01d3aa02445c70e916c26df4eb06ea3bc3ab4920eba139e60cc77409a7b2b002b95aab58a01ef25765e4651471bc9ec83f06e31b398cd890063639779000000000006000000000000000000000000ac8e86feeeef1e9996acd1115f6d1b796a9518c600000000000000220f01000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000007168518585d5bf16f62fefb346f365120738c4b0000612000000000000000000000000000000000000000000000000000000006363a890000000000000000000000000000000000000000000000000000000006363ba2404000000000000000000000000b97ef9ef8734c71904d8002f8b6bc66dd9c48a6e00060000000000000000000000e8d4a51000c6fa7af3bedbad3a3d65f36aabc97431b1bbe4c2d2f6e0e47ca60203452f5d6100010000000000000000000000e8d4a5100000000000000000000000000004068da6c83afcfa0e13ba15a6696662335d5b75000a0000000000000000000000e8d4a510000000000000000000000000002791bca1f2de4661ed88a30c99a7a9449aa8417400050000000000000000000000e8d4a51000000000000000000000000000870dc16249b860af63d671e02966b82ff44ac0a6eb15d7699592e1d8ddab0073499b17c515ad0630000000000000000000000000000000000000000000000000000000006363c258
```
