### ISSUE TITLE
node - solana watcher txHash fix

### ISSUE THREAD

**Issue by justinschuldt** [wormhole-foundation/wormhole#2364]
### Issue:
The solana transaction hash produced by the solana watcher is not the transaction identifier from the chain, it is the account ID. The base58 account ID from solana is concatenated to fit inside an eth hash in the guardian's solana watcher [here](https://github.com/wormhole-foundation/wormhole/blob/main/node/pkg/watchers/solana/client.go#L788-L789).

### Implementation:
The [`MessagePublication` struct](https://github.com/wormhole-foundation/wormhole/blob/main/node/pkg/common/chainlock.go#L17) will need to be updated to be a different type that is sufficiently long to hold Solana IDs. note, the comment on the struct property linked (`TODO: rename to identifier? on Solana, this isn't actually the tx hash`) is referring to the fact that the solana watcher stores the account ID in the `txHash` property. The concatenation to eth hash is not documented anywhere as far as I know.

### Relevance
The solana watcher will need to be updated to produce a transaction ID that matches the chain's before BatchVAAs are implemented for solana, or users will have to jump through hoops to translate what they get from the chain to the format produced by the guardian.

This malformed txHash is the reason looking up a solana transaction on the v1 explorer fails to find the message.

**Comment by evan-gray** [comment]
I’m fairly certain that all the relevant code accommodates this field being the Solana message account. Closing this as not planned given that batch VAAs, as designed when this issue was written up, was cancelled.
