### ISSUE TITLE
node: document and enforce better guardian parameters

### ISSUE THREAD

**Issue by evan-gray** [wormhole-foundation/wormhole#2503]
## Description and context
Right now the guardian doesn't check if the passed in endpoints will work before attempting to use them in process. This leads to things like an unsupported TLS endpoint being passed for `accountantWS` resulting in a log-only error in the accountant subroutine.

## Definition of done
The guardian should include documentation for all parameters for what is expected (format, features of endpoints) and then enforce those expectations at startup (or at least warn about them).

## Challenges
One challenge I could foresee is that startup shouldn't be blocked simply because a single chain's node is offline or unresponsive. Some checks might need to be downstream like when instantiating a watcher.

**Comment by bruce-riley** [comment]
Resolved by these PRs:
https://github.com/wormhole-foundation/wormhole/pull/3627
https://github.com/wormhole-foundation/wormhole/pull/3622
