### ISSUE TITLE
Tilt: Algorand keeps running on `tilt down`

### ISSUE THREAD

**Issue by hernandp** [wormhole-foundation/wormhole#2565]
## Description and context
When `tilt down` is executed, all containers are shut down except Algorand ones.

## Steps to reproduce
Initiate Algorand node support with 

```
tilt up -- --algorand
```

Wait for all containers to run (typically 7/7).

Shut down Tilt with:

```
tilt down
```

All containers will stop and shutdown gracefully, except Algorand ones (kmd, algod, indexer, etc).  The cannot be manually stopped due to the auto-restart behavior.

## Expected behavior
Everything that was started by the `up` command must be gracefully stopped.

## Solution recommendation
Probably there is something missing in Tiltfile regarding shutting down Algo containers.

**Comment by evan-gray** [comment]
You have to tilt down with the same flags https://docs.tilt.dev/cli/tilt_down.html
