### ISSUE TITLE
clients/js: refactor worm so that chain name is top-level

### ISSUE THREAD

**Issue by heyitaki** [wormhole-foundation/wormhole#2598]
Currently, commands in `worm` CLI are split by either chain or by functionality (eg `worm sui deploy` and `worm start-validator aptos`). This is confusing because functionality for any given chain may live in different top-level commands. We may want to consider refactoring the CLI such that all commands follow the format `worm <chain> <sub-commands>`

**Comment by AlberErre** [comment]
Hey @heyitaki I would love to work on this, could you assign me the issue? 👀

**Comment by heyitaki** [comment]
@AlberErre done! let me know if you'd like to discuss high-level design cc @evan-gray

**Comment by AlberErre** [comment]
Sure! I've been playing around and setting up the dev environment

The most painful command is definitely `worm start-validator <chain>`. Extracting this command and integrating it in both `worm aptos` and `worm evm` would be a quick win

Here is a PR refactoring it ✅ -> https://github.com/wormhole-foundation/wormhole/pull/2602

Although, I would like to get your feedback (@heyitaki @evan-gray) regarding other methods.

For instance, some methods like `worm generate`, `worm parse` or `worm contract <network> <chain> <module>` looks generic enough to be outside of the scope of any particular chain. Therefore, breaking the `worm <chain> <sub-commands>` pattern idea.

I would appreciate your input on this, as you probably have more context 🧠

**Comment by kcsongor** [comment]
Agreed that `worm parse` and `worm generate` don't really fit under any other chain. It's also true that some of the command hierarchy is a little ad-hoc. @heyitaki sounds like what you're looking for is some sort of consistent namespacing, would `worm vaa parse` and `worm vaa generate` make sense, i.e. introducing a `vaa` namespace alongside the chains?
In any case, those commands are used commonly enough that we may want to keep top-level aliases for them anyway. Moving `start-validator` under the chain makes sense to me, especially because the flags are different between each chain.

**Comment by heyitaki** [comment]
@kcsongor I like the addition of a `vaa` top-level command! Was thinking if we were going the top-level route, we might as well also extract things such as `deploy`,  `init`, `publish-message`, but you're right that these have chain-specific flags, so let's keep those as is.

Along with a `vaa` top-level command, what do you think about adding `info`, under which `chain-id`, `contract`, and `rpc` are moved under? Or if we're worried about the command itself getting bulky (e.g. `worm info contract <network> <chain> <module>`), perhaps we could coalesce them into `worm info [options]` where we can print info based on network, chain, or module depending on what's passed in.

**Comment by kcsongor** [comment]
`info` sounds good!

**Comment by AlberErre** [comment]
I really like the `worm info` initiative ✅ makes sense to group those `chain-id`, `contract`, and `rpc` together, as they all display contract/chain information.

On the other hand, I feel `worm vaa` is very domain specific. Until reading the docs, newcomers don't really know what a `VAA` is (myself included). Also, as @kcsongor suggested these commands are commonly known at the moment, adding an extra layer of abstraction there may make it more complex to use 🧩

**Comment by heyitaki** [comment]
Sounds good, let's add `info` and hold off on `vaa` for now then!

**Comment by AlberErre** [comment]
Great! 🚀 

I have created an additional PR implementing `worm info` namespace as discussed

Here it is ✅ -> https://github.com/wormhole-foundation/wormhole/pull/2603

A quick note, this MR is a follow up from https://github.com/wormhole-foundation/wormhole/pull/2602, which should be merged first 🚨
