### ISSUE TITLE
Significantly slower compilation with wormhole js sdk ^0.9.10

### ISSUE THREAD

**Issue by duxiaofeng-github** [wormhole-foundation/wormhole#2623]
## Description and context
Previously I was using @certusone/wormhole-sdk 0.9.8, and when I upgraded it to 0.9.10, 0.9.11, 0.9.12, the compilation was significantly slower than before, and it required more than 2048MB of memory. Otherwise, it threw out of memory error on the webpack compile phase.

So, I'm wondering why the SDK requires so much memory and slows my project.

## Solution recommendation
I look into the node_module and found there is no precompile file in it. All files are compiled on start-up, so can you provide the precompiled file on the npm package? At least I can add an alias to the webpack config file and skip all this source code compilation. This can save me a lot of time waiting for the webpack. Now it costs me more than 10+ mins to start up.

**Comment by duxiaofeng-github** [comment]
@aadam-10 can anyone help me on this?

**Comment by aadam-10** [comment]
hello @duxiaofeng-github, we have this in the pipeline which might help with the problem. perhaps you can try it out and report back, then we go from there? 

https://github.com/wormhole-foundation/wormhole/pull/2658

**Comment by duxiaofeng-github** [comment]
@aadam-10 I installed @certusone/wormhole-sdk@0.9.13, which looks better than @certusone/wormhole-sdk@0.9.12, but when I first installed and compiled the project, my local still needed 7 minutes

**Comment by duxiaofeng-github** [comment]
Can you provide a precompiled, bundled cjs/esm file in the dist folder? Then I can skip the compilation on my local, and only when I deploy the project to production, I will use webpack tree shaking.

**Comment by evan-gray** [comment]
The package is available via yarn/npm - is there a reason you are compiling from source? Please use the published packages.
https://www.npmjs.com/package/@certusone/wormhole-sdk 
https://yarnpkg.com/package/@certusone/wormhole-sdk

**Comment by duxiaofeng-github** [comment]
@evan-gray  no, it's not what i mean. i don't compile it from source. i mean you can provide a bundled and compressed dist file in npm package, then i don't need to use webpack to compile it again. webpack will tree shake it and compress it, these steps take a lot of time. i guess that's why webpack needs 10+ mins to finish the compilation.
