### ISSUE TITLE
sui: parallelize chain registrations

### ISSUE THREAD

**Issue by heyitaki** [wormhole-foundation/wormhole#2643]
A number of recent changes have slowed down the speed at which the sui container comes up in Tilt (e.g. re-requiring `const-gen` as a dependency, adding contract deployments/chain registrations`, etc.). An easy win to speed this up by 30sec - 1min would be to parallelize chain registrations.

**Comment by kcsongor** [comment]
good idea, I did a naive attempt in #2644, will see if it works. If the sui sdk queries a wallet nonce before submitting the transaction, then it won't work (because the concurrent txs wold have clashing nonces), and we might have to consider a more sophisticated approach

**Comment by kcsongor** [comment]
aside, but the `const-gen` script also runs unnecessarily slow, we could speed that up by either parallelising the bash script itself, or consider rewriting it in javascript -- most of the time is spent in the startup time of node, and in particular loading dependency modules

**Comment by kcsongor** [comment]
Closed by #2644.

**Comment by heyitaki** [comment]
Although #2644 ran into some concurrency issues, this issue has now been resolved by https://github.com/wormhole-foundation/wormhole/pull/2806/commits/35c9d601f3bf06875e9392c787e22d7ac386da51 in which I combined all chain registrations into one transaction block. Now completes in a couple seconds :D
