### ISSUE TITLE
Ethereum -> Algorand not working when using WalletConnect in both source and destination

### ISSUE THREAD

**Issue by d13co** [wormhole-foundation/wormhole#2773]
## Steps to reproduce

1. Connect Ethereum source account with WalletConnect
2.  Choose token, amount
3. Start connecting Algorand destination account with WalletConnect (i.e. Pera or Defly)

## Experienced behavior

The page is replaced by the error message "An unexpected error has occurred. Please refresh the page." 

![1682263499](https://user-images.githubusercontent.com/95573415/233849477-275864a5-3fa3-4779-9ccf-c4d47e80f244.png)

## Expected behavior

Pera Connect / Defly Connect modal shows and I can proceed to connect my account

## Solution recommendation

![1682263484](https://user-images.githubusercontent.com/95573415/233849472-6cb3e00d-2426-429e-9922-85b034727427.png)

The console logs "address seems to be malformed", which is the algorand SDK error when an address provided to the SDK is not a valid Algorand address

This leads me to believe that the source and destination WalletConnect sessions are not independent as they should, but instead the EVM address (0x12357890123...) from the source session is being fed into the algorand SDK, causing this error.

**Comment by evan-gray** [comment]
Hi @d13co, thanks for reporting. This is the monorepo for Wormhole, while the issue is in the Portal front-end, which is maintained by xLabs over at https://github.com/XLabs/portal-bridge-ui. Would you mind recreating the issue there? Meanwhile I will reach out to their team as well.

**Comment by d13co** [comment]
Thanks, opened it here: https://github.com/XLabs/portal-bridge-ui/issues/81
