### ISSUE TITLE
Set WETH address of Arbitrum

### ISSUE THREAD

**Issue by mizdler** [wormhole-foundation/wormhole#2796]
WETH address is unset and causes `wrapAndTransferETH` `completeTransferAndUnwrapETH` functions to fail.

I believe `[0x82af49447d8a07e3bd95bd0d56f35241523fbab1](https://arbiscan.io/address/0x82af49447d8a07e3bd95bd0d56f35241523fbab1)` is the canonical wrapped ETH contract on Aribtrum.

I suggest setting it as the WETH address.

**Comment by evan-gray** [comment]
@mizdler These functions purposefully fail on Arbitrum. That is because `ETH` on Arbitrum is already wrapped by the Arbitrum bridge. Sending it via Wormhole would result in double-wrapped (Arbitrum-bridged, Portal-wrapped) `ETH` and would not be fungible with WETH anywhere else.

**Comment by mizdler** [comment]
@evan-gray Thank for your quick reply.

Let's say we a have pool of this double-wrapped ETH with ETH on Solana
Users can swap and receive the native currency of Arbitrum. which I think is a valid use case.

Why not leave this decision to integrator? 
If Portal doesn't want users to swap token X I think it's better to prevent it on dApp level instead of contract level.

**Comment by evan-gray** [comment]
Thanks for the rationale. I’ll reopen this and circulate with the contributors to see if we can get consensus and make a recommendation.
