### ISSUE TITLE
Solidify decision on using a 'safe' call to the relayProvider

### ISSUE THREAD

**Issue by derpy-duck** [wormhole-foundation/wormhole#2814]
Currently in the code, we perform a call to 'isChainSupported' of the relay provider's contract through a **low level call** rather than doing it directly

(in CoreRelayerDelivery.sol)
```
(bool success, bytes memory data) = getWormholeRelayerCallerAddress().call(
                abi.encodeWithSelector(IForwardWrapper.safeRelayProviderSupportsChain.selector, provider, instruction.refundChain));
```

The purpose of this is to protect against malicious relay provider behavior: specfically, if the relay provider, in their implementation of isChainSupported, reverts -- then, the 'safe' call returns false rather than causing the whole transaction to revert. 

I claim this protection isn't useful; specifically: they can reproduce the exact same outcome (the full transaction reverts) anyways: by simply not doing the transaction in the first place. Given this is the case, including this 'safe' call doesn't make much sense because it doesn't protect against anything, since the exact same end goal can be achieved anyways. 

so, I am proposing we replace this line of code with a simple `provider.isChainSupported(instruction.refundChain)`

**Comment by scnale** [comment]
Moreover, this should be a static call, shouldn't it? It's better to use plain function calls as provided by the language unless there's a very good reason not to.

**Comment by derpy-duck** [comment]
ah yes good point ^, will make it a static call
