### ISSUE TITLE
Implement new data availability scheme

### ISSUE THREAD

**Issue by leoluk** [wormhole-foundation/wormhole#282]
Design doc: https://forge.certus.one/plugins/gitiles/wormhole/+/refs/heads/dev.v2/design/0005_data_availability.md

- [X] Store signed VAAs in local database
- [X] API endpoint to retrieve signed VAAs
- [X] Publish signed VAAs to gossip
- [X] Store missing received VAAs to local database
- [ ] Log message IDs everywhere
- [ ] #295
- [x] Vote only mode

**Comment by arijitAD** [comment]
@leoluk I am interested in this use case. Can I contribute to complete the remaining tasks?

**Comment by leoluk** [comment]
Could you describe your use case?

**Comment by arijitAD** [comment]
We want to observe the Avalanche chain(C-chain) and reach a consensus and store the VAA in LevelDB.

**Comment by hendrikhofstadt** [comment]
Mostly deprecated by reobervations
