### ISSUE TITLE
typescript: use NPM workspaces

### ISSUE THREAD

**Issue by heyitaki** [wormhole-foundation/wormhole#2863]
We should use the local version of the WH SDK in `clients/js` (as opposed to pinning a version of the published package on NPM) because it would greatly speed up development since contributors would no longer need to deal with publishing new package versions just for development or deal with imports from outside of the package. We can use NPM workspaces to accomplish this

**Comment by evan-gray** [comment]
Closing as the SDK redesign has moved out of the monorepo which presents a different challenge for cli use / maintenance in this repo but like makes this issue irrelevant.
