### ISSUE TITLE
typescript: enforce consistent formatting

### ISSUE THREAD

**Issue by heyitaki** [wormhole-foundation/wormhole#2867]
We should enforce consistent style + formatting across all TS code (and potentially Rust/Go) via a CI-enforced lint check. This will optimize devX because it'll be easier to parse code at a glance and should reduce human error.

**Comment by ArslanYM** [comment]
@aadam-10 Do you want some initiation on this issue ( more like a feature) ?

**Comment by aadam-10** [comment]
hi @ArslanYM, for the time being we'd like to keep this one for the core contributors as it possibly needs a lot of back and forth communication. however, I invite you to check out https://github.com/wormhole-foundation/wormhole/issues/2866 which we do need help with.

**Comment by kcsongor** [comment]
done in #3176
