### ISSUE TITLE
clients/js: set `"strict": true` in `tsconfig.json`

### ISSUE THREAD

**Issue by heyitaki** [wormhole-foundation/wormhole#2869]
Currently, `strict` is set to `false` in `clients/js`, but should absolutely be set to `true` to prevent bugs involving undefined/null values.

**Comment by haseeb-xd** [comment]
Can I work on this as I am still new to open-source?

**Comment by heyitaki** [comment]
Hey @haseeb-xd, this is actually done in #2885, which will likely be merged in sometime later this week

**Comment by heyitaki** [comment]
Closed by #2885
