### ISSUE TITLE
Errors during processing payment for RelayerProviders are ignored.

### ISSUE THREAD

**Issue by ankurdubey521** [wormhole-foundation/wormhole#2894]
https://github.com/wormhole-foundation/wormhole/blob/d560a95e08c08c774fbbd2e69cc9c1e811851313/ethereum/contracts/relayer/coreRelayer/CoreRelayerSend.sol#L63

Hello, I noticed that in the call to the `RelayerProvider` contract fails, the error is not handled in the parent call. This could result in a DeliveryVAA being emitted without the relayer receiving payment for processing it. 
I wanted to understand if there's a reason for not reverting the whole transaction if payment to the relayer provider fails.

**Comment by derpy-duck** [comment]
Closed with #2998
