### ISSUE TITLE
Security Fix - Don't use Try Catch

### ISSUE THREAD

**Issue by derpy-duck** [wormhole-foundation/wormhole#2929]
1. Try Catch doesn't catch the error of an address not having any code

ALSO,

2. The callee can sometimes cause the caller to revert during memory expansion cost payment at the returndata binding. in order to avoid allowing that you have to manually implement returndata copying with a capped size and reserved gas

**Comment by derpy-duck** [comment]
Potentially any fixes also would have to be applied for the low-level calls for cross-chain refund and for executeInstruction as well

**Comment by scnale** [comment]
I was thinking that another option is to charge for return data length that exceeds a certain size. I don't think we should opt for this solution now but it could be interesting if we ever decide to implement forward requests through return data instead of nested calls like we are doing now.

**Comment by scnale** [comment]
A call with an upper bound on return call data is being implemented in #2934. It doesn't address this issue in its entirety for now though.

**Comment by scnale** [comment]
Actually, after reviewing other instances of `try/catch` in our contracts, they're all towards `this` so we should be fine. Preflight checks for function calls shouldn't fail with those.

**Comment by scnale** [comment]
>Potentially any fixes also would have to be applied for the low-level calls for cross-chain refund and for executeInstruction as well

I think that the call to `executeInstruction` can be left as a `try/catch`. I'm thinking that payment calls might benefit from using the low level call though. This includes the calls that the `payRefundToRefundAddress` function does.
