### ISSUE TITLE
Discover or specify public IP address in cloud environments

### ISSUE THREAD

**Issue by leoluk** [wormhole-foundation/wormhole#299]
libp2p doesn't currently discover and advertise a node's public IP address in a NAT-ed cloud environment.

**Comment by SEJeff** [comment]
Would it make sense to hit the provider specific endpoints, or call out to one of several “what is my external ip” services?

**Comment by leoluk** [comment]
In theory, we can use libp2p itself - other nodes on the network can tell us our public IP

**Comment by aadam-10** [comment]
Please reopen if this is still relevant
