### ISSUE TITLE
ci tests failing on main: Algorand

### ISSUE THREAD

**Issue by tbjump** [wormhole-foundation/wormhole#3061]
Algorand ci tests are repeatedly failing on a PR that doesn't touch Algorand: https://github.com/wormhole-foundation/wormhole/actions/runs/5205004596/jobs/9390926964?pr=3055

**Comment by barnjamin** [comment]
It looks like its checking out a v old version of go-algorand then running sandbox up cmd

https://github.com/wormhole-foundation/wormhole/blob/main/algorand/runPythonUnitTests.sh#L10

Maybe makes sense to use something besides sandbox for CI stuff?

Beaker lib uses the makerx image https://github.com/algorand-devrel/beaker/blob/master/docker-compose.yml
But there are official ones available now: https://developer.algorand.org/articles/introducing-official-algod-docker-containers/

**Comment by barnjamin** [comment]
Also the sudden failing is probably because of this change https://github.com/algorand/sandbox/pull/183 so a short term fix might just be to checkout a version prior to that. 

Still should figure out a better long term path though
