### ISSUE TITLE
Timestamp check for late observation is ineffective

### ISSUE THREAD

**Issue by evan-gray** [wormhole-foundation/wormhole#3172]
https://github.com/wormhole-foundation/wormhole/blob/b35091821420e6a6974f431f0f6fe3becdd3f246/node/pkg/processor/message.go#L106

Both timestamps will be the same, as they are derived from the block. The result of the subtraction will therefore be 0 and never > 30. Probably just remove this block...

**Comment by bruce-riley** [comment]
This issue was fixed by PR #3307.
