### ISSUE TITLE
Adding more EVM chains

### ISSUE THREAD

**Issue by macalinao** [wormhole-foundation/wormhole#334]
Hey all-- we'd like to use Saber as an on-ramp to Solana, and we think Avalanche, Polygon, and Celo would be good candidates as chains to support

What is involved in adding another EVM chain?

**Comment by lijiang2087** [comment]
and harmony as a full evm compatible chain

$100m+ tvl on sushi on harmony: https://analytics-harmony.sushi.com/
and
$100m+ tvl on harmony's bridge to ethereum and bsc: https://bridge.harmony.one/tokens

**Comment by evan-gray** [comment]
Closing as Avalanche, Polygon, and Celo are all fully supported by Wormhole and Portal.
