### ISSUE TITLE
Adding more Cosmos chains

### ISSUE THREAD

**Issue by macalinao** [wormhole-foundation/wormhole#335]
It would be very useful if Wormhole could support other Cosmos chains, allowing one to bridge any Cw20 + SDK asset. Cosmos is both fast and focused on cross-chain bridges, so it would be a great intermediate chain for chains that are not on Wormhole's roadmap.

What's the work involved in building this and getting validators to run this?

**Comment by leoluk** [comment]
The biggest obstacles are incentives (convincing the guardian set that running an extra node is worth the operational overhead), on-chain program development and node integration work.

The Terra CosmWasm program could probably be easily adapter to other chains. For Cosmos chains with CosmWasm support, a native module would have to be built.

**Comment by evan-gray** [comment]
The `cosmwasm` contracts now generically support cosmwasm 1.0.0. It’s possible that wormchain will bring even more cosmos ecosystem support. That said, closing this issue since it’s not for a particular chain so it can’t really be completed. 🙃
