### ISSUE TITLE
Wormchain: can't resume transaction. Osmosis -> Eth

### ISSUE THREAD

**Issue by omniwired** [wormhole-foundation/wormhole#3426]
## Description and context

Bridging from Osmosis (cosmos) into eth fails.

The transaction IBC from Osmosis into wormchain, but then the portal UI fails, and the transaction and the funds are stuck in the bridge.
What is missing is the redemption portion of the process (in the Ethereum blockchain).

The completed tx from Osmosis is found, but the "indexer" or maybe "watcher" fails to do the link from these 2 blockchains; which results in being unable to finish the redeem step in the target chain.

## Steps to reproduce

More information in here:

https://github.com/XLabs/portal-bridge-ui/issues/389

1. Visit https://www.portalbridge.com/cosmos 
2. Select source chain to be Osmosis
3. Target chain to be Ethereum
4. The UI times-out, the funds are transferred from the Osmosis chain, but can't be redeemed in Ethereum.

Extra information:

Using a not hardware wallet, to avoid the [this issue](https://github.com/XLabs/portal-bridge-ui/issues/389).

here is the TX https://www.mintscan.io/osmosis/tx/0396E9EF40FF04422478BB0149F59F7C910B50F19AA27EAFFC591017F7E64CD5

package data was:
```
{
  "amount": "118508800",
  "denom": "transfer/channel-2186/factory/wormhole14ejqjyq8um4p3xfqj74yld5waqljf88fz25yxnma0cngspxe3les00fpjx/5TSQTEhJ5Q6r1YqCmCxTRSPiV2pGx5rZUQf6g2XH4e1b",
  "memo": "{\"gateway_ibc_token_bridge_payload\":{\"gateway_transfer\":{\"chain\":2,\"nonce\":9185,\"recipient\":\"AAAAAAAAAAAAAAAAPv6LvvnLjFy2yWI7iFY5ERqaZoE=\",\"fee\":\"0\"}}}",
  "receiver": "wormhole14ejqjyq8um4p3xfqj74yld5waqljf88fz25yxnma0cngspxe3les00fpjx",
  "sender": "osmo1c2t58ydw6ww7ukrm66xu67y2hmz66der30elg8"
}
```

![telegram-cloud-photo-size-5-6118421320107669761-y](https://github.com/wormhole-foundation/wormhole/assets/322761/1c6c2af9-93bd-492d-94a4-4fb6de28f6ab)

![telegram-cloud-photo-size-5-6118350143909641655-y](https://github.com/wormhole-foundation/wormhole/assets/322761/a3fba7e7-60cb-4b8f-b5d3-fe403f69480c)

cc: @nik-suri

**Comment by aadam-10** [comment]
hello, please use discord for this kind of request: https://discord.gg/wormholecrypto
