### ISSUE TITLE
CCQ: Should it peg Prometheus Metrics?

### ISSUE THREAD

**Issue by bruce-riley** [wormhole-foundation/wormhole#3433]
Should consider whether or not either or both the `ccq_server` and the ccq components in the guardian should peg metrics.

**Comment by evan-gray** [comment]
I'm definitely in favor of prometheus metrics for both. at least some sort of basic requests received, dropped, success. maybe breakdown per chain as well?

**Comment by SEJeff** [comment]
Indepth p2p and http stats are important to monitor the health of the query server. This makes it much easier to productionize and makes your SREs^WEvan's happy.
