### ISSUE TITLE
0x0c106211fb43ec4d0e05b3eb25a0537078aaace066bbbeadcdc71f6c07fc3681

### ISSUE THREAD

**Issue by Ali3447** [wormhole-foundation/wormhole#3564]
## Steps to reproduce

1.
2.
3.

## Solution recommendation

I bridge Tokens have been deducted from my wallet, but I haven't received anything in Solana yet and the team has no response.

**Comment by wyatt1611** [comment]
Hello, I would like to ask how you contacted the team? I did not receive any token after I transferred the cross-chain transfer today.

**Comment by claudijd** [comment]
Try https://discord.gg/wormholecrypto

**Comment by SEJeff** [comment]
As @claudijd said, please join the discord and speak with one of the community managers. This bug tracker is for bugs in the node software. Unfortunately, we aren't the best folks to help you whereas the community managers absolutely are.

Sorry for the inconvenience.
