### ISSUE TITLE
how to deserialize solana posted vaa account onchain

### ISSUE THREAD

**Issue by 0xshitbird** [wormhole-foundation/wormhole#3589]
when submitting a post_vaa instruction to wormhole a posted_vaa account is created, how can this account  be deserialized from another solana program? 

i try use the following but decode fails due to magic mismatch

https://github.com/wormhole-foundation/wormhole/blob/bf9660f75bdf14c50746d66a63735e098f9cd988/solana/bridge/program/src/accounts/posted_vaa.rs#L50

because of solana dependency requirement i unable to import the above listed code as a dependency, so i copied the relevant code to another repository https://github.com/0xshitbird/wormhole-lite/blob/11f0ef3b1cd2aaad4cb9aef55c340aadfa59d442/solana/src/state/vaa.rs#L15-L80

**Comment by swimricky** [comment]
are you calling the `post_vaa` ix through CPI or from a client? if through CPI you might need to reload the account after invoking the CPI call before trying to deserialize. can you post the code snippet on how you're trying to deserialize the posted_vaa account?

**Comment by 0xshitbird** [comment]
@swimricky I'm calling `post_vaa` through CPI, however the instruction that I'm attempting to deserialize the vaa account in is sent in a different transaction so there shouldn't be an issue with reloading the account.

I'm attempting to deserialize the account like so, where the `deserialize` method is provided by [this trait `impl`](https://github.com/0xshitbird/wormhole-lite/blob/11f0ef3b1cd2aaad4cb9aef55c340aadfa59d442/solana/src/state/vaa.rs#L60)

```
      let posted_vaa_data = wormhole_solana_lite::state::vaa::PostedVAAData::deserialize(
        &mut &self.vaa_account.data.borrow()[..]
      )?;
```

With `vaa_account` is  an `AccountInfo<'info>`

**Comment by swimricky** [comment]
If you're using anchor you can follow the setup here that uses the wormhole-anchor-sdk

https://github.com/wormhole-foundation/wormhole-scaffolding/blob/main/solana/programs/01_hello_world/src/context.rs

**Comment by evan-gray** [comment]
Concur that `wormhole-anchor-sdk` should do the trick.
