### ISSUE TITLE
Portaltokenbridge isn't detecting installed wallets extension,always ask to install them then redirects to official wallet download page

### ISSUE THREAD

**Issue by mardaquat** [wormhole-foundation/wormhole#3621]
## Description and context
Portaltokenbridge isn't detecting installed wallets extension,always ask to install them then redirects to official wallet download page

## Steps to reproduce
With ubuntu 23.04, using firefox 111.0.1(64-bit) you are not able to connect your installed wallet exenstions

## Experienced behavior
cant connect installed wallet

## Expected behavior
wallet should be detected and be able to connect

**Comment by aadam-10** [comment]
hello, please use discord for this kind of request: https://discord.gg/wormholecrypto
