### ISSUE TITLE
Bridge not confirmed

### ISSUE THREAD

**Issue by yunseongmi** [wormhole-foundation/wormhole#3729]
From portal token bridge to osmosis to Aptos, the bridge is still unbridgeable after 24 hours. What should I do?

4155F450BDB406A4A7C8F64186A911139C886658973B368780173A29B1668FAB

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by aadam-10** [comment]
hello, please use discord for this kind of request: https://discord.gg/wormholecrypto
