### ISSUE TITLE
Bridge error 

### ISSUE THREAD

**Issue by Tiwatopeo** [wormhole-foundation/wormhole#3792]
From portal token bridge from  Eth  to sol, the bridge is still unbridgeable after 24 hours. What should I do?

**Comment by nghiaeuro123** [comment]
Tx Hash:
[0x90492e5dd973d1074a02075ded0c64af73b061a0be401c7ef1e4782306628678](https://bscscan.com/tx/0x90492e5dd973d1074a02075ded0c64af73b061a0be401c7ef1e4782306628678)
40days PENDING REDEEM
can you help me please

**Comment by nghiaeuro123** [comment]
<img width="1440" alt="2" src="https://github.com/wormhole-foundation/wormhole/assets/153918734/a9de102f-48cc-48aa-b4cb-93120ebe57e5">
<img width="1440" alt="1" src="https://github.com/wormhole-foundation/wormhole/assets/153918734/e24ca539-b60a-4e69-899a-d69b624412fe">

**Comment by aadam-10** [comment]
hello, please use discord for this kind of request: https://discord.gg/wormholecrypto
