### ISSUE TITLE
VAA limit / the underlying liquidity of the bridge itself issues (not the token transferred).

### ISSUE THREAD

**Issue by montax5** [wormhole-foundation/wormhole#3793]
## Description and context
Would be also great to have a table updated regularly with the available liquidity / expected waiting period for various bridges like blockchain ABC > blockchain XYZ : available liquidity XXX, expected VAA time YYY.

A update on this would be helpful. Thanks

**Comment by 6thmiracle** [comment]
i agree

**Comment by evan-gray** [comment]
There are no liquidity limitations for the Token Bridge as it utilizes wrapped tokens, not cross-chain swaps. The governor limits and accountant balances are visible on [the dashboard](https://wormhole-foundation.github.io/wormhole-dashboard/#/).
