### ISSUE TITLE
Airdrop shows up as not eligible even though I tried everything 4 months ago

### ISSUE THREAD

**Issue by Pranshu000** [wormhole-foundation/wormhole#3818]
**I can show you whatever proof you want, please correct it.
Please check my address once, all of you, I did everything to him 4 months ago but did not get it, just a few airdrops.**

**This is My address** :- 0x8458a4EeCbF640eC4b64180fdeBB5C8DCba41EE1 
**And here is your website** :- 0x8458a4EeCbF640eC4b64180fdeBB5C8DCba41EE1
![Screenshot 2024-03-08 151202](https://github.com/wormhole-foundation/wormhole/assets/91258027/10c18dd3-1c88-498d-a361-769fe7cdde1b)

I have given you a photo so you can see everything

_I just request you with folded hands to check the address again. If I am wrong then don't worry but please check once._

**Comment by aadam-10** [comment]
this is not related to this repository

**Comment by Pranshu000** [comment]
> this is not related to this repository

Look at me, I am saying the way you described it, I think you are wrong, why don't you say that this has happened with people like us, once again check the address, after giving such clear proof to everyone, you said. do
