### ISSUE TITLE
Display fees

### ISSUE THREAD

**Issue by evan-gray** [wormhole-foundation/wormhole#400]
As a user about to perform a transfer, I want to know what the fees are. At least display the bridge fees.

**Comment by imsys** [comment]
An example of how it is shown in the polygon bridge.
![Selection_283](https://user-images.githubusercontent.com/911254/134222346-a19a68e2-c244-4bd8-a1ad-6a0ea979195b.png)

**Comment by evan-gray** [comment]
Hi @imsys , thanks for the screenshot! There's a very basic implementation coming for Ethereum soon, but definitely want to consider how it can be further enhanced.

**Comment by evan-gray** [comment]
Closing as bridge_ui was removed in https://github.com/wormhole-foundation/wormhole/pull/1468
