### ISSUE TITLE
Problem with Wrapped Dogeverse Tokens - Invalid Smart Contract

### ISSUE THREAD

**Issue by Mcheikhali** [wormhole-foundation/wormhole#4023]
Hello Wormhole Support Team,

My name is Mohammad, and I'm writing to you regarding an issue I encountered while using the Wormhole bridge to transfer Dogeverse tokens from my Solana wallet to my MetaMask wallet.

**Transfer Details:**
- **Source:** Solana wallet
- **Destination:** MetaMask wallet
- **Token:** Dogeverse
- **Provided Smart Contract Address:** 0x3AEd6928b4BDbca64C82E05ECbdb2dA0FD920912

After completing the transfer, I added the smart contract address to my MetaMask wallet and checked it on Etherscan. Unfortunately, it appears that this contract address is not valid, and no platform or wallet recognizes it, as the token value always shows as zero.

I am facing a significant issue because of this, as I paid for the transfer, and now I am unable to retrieve the value of my tokens or unwrap them.

Please assist me in resolving this issue as soon as possible. I need to ensure the authenticity of the tokens and retrieve their original value.

Thank you for your understanding, and I look forward to your prompt response.

Best regards,
Mohammad

**Comment by Pacsai** [comment]
You have registered a token, thus creating an extra coin that has no value. Bring your coin back to the Solana chain using Wormhole and from there you can transfer it to Ethereum using the more expensive bridge technology. Unfortunately, solana is not possible with wormhole technology even in terms of dogeverse. (I'm not a developer at either wormhole or dogeverse) So someone will confirm my writing

**Comment by scottdax1** [comment]
Hey @Mcheikhali 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID SOL07638
Please see the link below to our dedicated support line:
[solana Support Requests ](https://dappscustomersupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by aadam-10** [comment]
hello, could you please open a ticket on discord for advice: https://discord.com/invite/wormholecrypto

**Comment by Mcheikhali** [comment]
Your mother is a bitch, you are fucking thief nothing more than shit
because a shit pig fucked your mother in his shit so they produce a son of
a bitch like you feed him self from stoling people money
