### ISSUE TITLE
Error when creating token account for mint that doesn't exist

### ISSUE THREAD

**Issue by evan-gray** [wormhole-foundation/wormhole#488]

**Comment by ajpatt61** [comment]
I transferred SRM from metamask to Solflare and the mint address assigned during the transfer resulted in an unrecognized token in my Solflare wallet
How can I get the SRM mint address re-assigned?

**Comment by evan-gray** [comment]
Closing as bridge_ui was removed in https://github.com/wormhole-foundation/wormhole/pull/1468
