### ISSUE TITLE
Received Token from metamask ETH to SOL phantom wallet, but as NFT 

### ISSUE THREAD

**Issue by BLACKoin** [wormhole-foundation/wormhole#528]
**has same issue:** @leoluk @maromandarino

ETH Txn: 0x9560685ee29f28e76b522c9338f080c27f67d1e184c0348ba76ac52f75dbf253
Sollana wallet address: PQJVRCJ7rtpvZXFXEWXCW9i91hN8p4hxoqeuHjiCrDP
sent to: AoyQUXh5GSnAmfvUTGTfLvRrazYCegpistkLL3MArwoj
 
![image](https://user-images.githubusercontent.com/92128631/136478939-3b49ae34-f6fa-4284-b757-7564a1110060.png)

![image](https://user-images.githubusercontent.com/92128631/136478987-0e57e299-f560-442d-ba2a-ef30d44d3343.png)

**Comment by BLACKoin** [comment]
thanks Ill have to make sure this is not a scam

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by leoluk** [comment]
It's a scam.
