### ISSUE TITLE
Create token account on Solana should be part of redeem flow

### ISSUE THREAD

**Issue by chrisirhc** [wormhole-foundation/wormhole#569]
Posting this mainly for discussion. Curious what folks think about this.

A couple of reasons for this:
1. It'd be possible to batch this creation as part of #485 if the Solana transactions are batched.
2. Simplifies bridging to Solana if the token is attested, so it doesn't require any transactions on the Solana side until redeeming (which could be a single batch of transactions see 3).
3. It's possible to go through redeem flow and redeem for a transaction that may have been initiated without the token account created (if it wasn't created via the wormhole bridge UI).

**Comment by evan-gray** [comment]
Hi @chrisirhc. I agree that this is possible, but only when the redeemer is the wallet owner. If I recall correctly, the wallet owner has to have signed the transaction to create the associated token account. In the bridge ui, there is code to check whether or not the associated account has been created in the redeem step (though it doesn’t attempt to put it in the series of transactions). The reason for forcing the user to create it up front was so that anyone could perform the redeem step.

All that said, I was hoping to make a relayer example that would show how to have the owner sign a transaction that could then be paid for by the relayer in order to complete a transaction where the owner had no SOL. 🙂

happy to hear your thoughts

**Comment by chrisirhc** [comment]
Ah, that makes sense completely though I was reading the create token code and while the wormhole code assumes the recipient is the payer and owner of associated account, it does seem like the program was designed with others able to pay for the creation of the token account. (Reference doc: https://spl.solana.com/associated-token-account )

Also referenced code:
https://github.com/certusone/wormhole/blob/d4ea78d2ca1f7921ed7a6778d0fa49219125e6ca/bridge_ui/src/components/SolanaCreateAssociatedAddress.tsx#L127

I could be completely off on this though. Appreciate your thoughts here already as it is. :)

**Comment by evan-gray** [comment]
Yea, I will have to double-check on that creation code! Thanks for pointing it out. I’ll leave this open for the time being as a reminder.

**Comment by chrisirhc** [comment]
After digging into this a bit more, looks like the provided target recipient address needs to be the token account address (not the public key of the Solana wallet owner):

https://github.com/certusone/wormhole/blob/c7c9e52e1d8b792719d5dcadf63ed8b8742a542e/bridge_ui/src/hooks/useSyncTargetAddress.ts#L67-L70

As such, the token account needs to be created before the first transfer, and the address used in the transaction from the source chain, for the first transfer operation.

One potential proposal:
* Store the owner address in the VAA in addition to an optional token account address, and verify the owner address of the provided token account during redemption. 
* The complete_wrapped function to can take an optional token account address. Default to using the associated token account address, fail the transaction if it is not is available, and not provided.

**Comment by evan-gray** [comment]
That is correct that the target address is the token account, not the wallet, and it needs to be created before redeeming (completing the transfer on Solana).

Not sure a change to the VAA is most effective (though there have been some ideas for different use cases there may be some shortcomings). If a front-end wanted to use a relayer, they should be able to simply pass the requisite data along with the signed VAA. (Given the the front-end needed to know the wallet in the first place to determine an associated token account.) Hoping I can draft up an example within the next week and get some thoughts / feedback.

**Comment by evan-gray** [comment]
Relates to #1309
