### ISSUE TITLE
Add Kovan to Testnet

### ISSUE THREAD

**Issue by ngundotra** [wormhole-foundation/wormhole#652]
It seems like its because the Covalent web3 api does not support reading NFTs from Goerli/Ropsten... 

Can this be documented as a WIP?

**Comment by evan-gray** [comment]
You should be able to manually enter a contract address and token id 🙂 but yes we can also look into adding Kovan

**Comment by ngundotra** [comment]
Hey @evan-gray , sorry if this is dumb question, but how can I manually add a contract address & token id?

**Comment by evan-gray** [comment]
No worries @ngundotra , after connecting your wallet you should be able to click “select token” and paste the contract and token id the two text fields towards the top of the dialog that say “Search name or paste address” and “Token Id”

**Comment by evan-gray** [comment]
Closing as Kovan has been deprecated https://ethereum.org/en/developers/docs/networks/
