### ISSUE TITLE
Solana to Terra: wormhole network consensus / requested VAA not found in store

### ISSUE THREAD

**Issue by ndankajapa** [wormhole-foundation/wormhole#773]
Hi there,

My transaction got stuck at "waiting for wormhole network consensus" when I was transferring UST from Solana to Terra. The tokens are stuck in between networks.

When I try to redeem from the transaction signature, Wormhole says "requested VAA not found in store"

Any ideas to retrieve my tokens? Thanks.

Here's the signature:

https://explorer.solana.com/tx/5k1XLh4X2YcmCH3Q8aijhFdjKbYhPZgjqErxLjFSqY3bfPQTFryPHejtFAnny4ZLD2nf7ppQUyxrSdKHLULifh8u

**Comment by suzzax** [comment]
Hello! You'll be able to redeem these tokens in your Terra wallet by following the redeem process:
1) Go to https://portalbridge.com/#/redeem
2) Paste in the signature of the above transaction you've provided
3) Click recover
4) Click redeem.

Feel free to reach out to our community managers on discord for more support!  https://discord.gg/wormholecrypto

Thank you!
