### ISSUE TITLE
Problem in fetching signedVAA in backend service

### ISSUE THREAD

**Issue by masoudsafa** [wormhole-foundation/wormhole#799]
Hey guys
i'm developing an dApp and have a bit problem fetching signedVAA
i think the problem is with grpc-web protocol. because javascript can fetch data but calling signedVAA from backend gets empty body. can you help me with that?
can you give me a rest api for that? or even grpc that works from backend

**Comment by bolshoytoster** [comment]
@masoudsafa could you share the code you're using to fetch it from javascript and from the backend?

**Comment by evan-gray** [comment]
Are you using the node http transport? (see our examples, like the integration tests) https://github.com/certusone/wormhole/blob/dev.v2/sdk/js/src/token_bridge/__tests__/integration.ts
