### ISSUE TITLE
"SenderAddress" always empty

### ISSUE THREAD

**Issue by Biuni** [wormhole-foundation/wormhole#860]
Hi to everyone!
Why the "SenderAddress" attribute in "ChainDetails" is always empty for all the transaction searched in the explorer?
(Example: https://wormholenetwork.com/explorer/?emitterChain=2&emitterAddress=0000000000000000000000003ee18b2214aff97000d974cf647e7c347e8fa585&sequence=23687)

There's an alternative way to go back to the sender address?

Thanks in advance!

**Comment by aadam-10** [comment]
The explorer doesn't always have the transaction details unfortunately, but you can always use etherscan.io to find the transaction with the matching sequence number. The new Wormhole explorer project aims to improve this experience: https://github.com/wormhole-foundation/wormhole-explorer
